// public/templates/Template 12/src/components/sections/EventDetails.tsx
"use client";

import React from 'react';
import { motion } from 'framer-motion';
import { MapPin, Clock, Calendar, ExternalLink } from 'lucide-react';
import Image from 'next/image';
import TornEdge from '../ui/TornEdge';
import VintageOrnament from '../ui/VintageOrnament';

const EventDetails = () => {
  const Card = ({ title, date, time, location, gmapsLink }: any) => (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="bg-white/50 backdrop-blur-md border border-vintage-gold/20 p-8 md:p-12 rounded-3xl relative overflow-hidden group hover:border-vintage-gold/50 transition-all duration-500 shadow-2xl"
    >
      <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:opacity-20 transition-opacity grayscale sepia">
        <VintageOrnament className="w-32 h-32" />
      </div>
      
      <h3 className="script-text text-6xl text-vintage-brown mb-8 gold-glow">{title}</h3>
      
      <div className="space-y-8 text-left relative z-10">
        <div className="flex items-start gap-5">
          <div className="bg-vintage-gold/10 p-4 rounded-full text-vintage-gold border border-vintage-gold/20 shadow-inner">
            <Calendar size={22} />
          </div>
          <div>
            <p className="serif-text font-bold text-vintage-brown uppercase tracking-widest text-xs mb-1">Hari / Tanggal</p>
            <p className="serif-text text-vintage-brown text-lg weathered-text">{date}</p>
          </div>
        </div>

        <div className="flex items-start gap-5">
          <div className="bg-vintage-gold/10 p-4 rounded-full text-vintage-gold border border-vintage-gold/20 shadow-inner">
            <Clock size={22} />
          </div>
          <div>
            <p className="serif-text font-bold text-vintage-brown uppercase tracking-widest text-xs mb-1">Waktu</p>
            <p className="serif-text text-vintage-brown text-lg weathered-text">{time}</p>
          </div>
        </div>

        <div className="flex items-start gap-5">
          <div className="bg-vintage-gold/10 p-4 rounded-full text-vintage-gold border border-vintage-gold/20 shadow-inner">
            <MapPin size={22} />
          </div>
          <div>
            <p className="serif-text font-bold text-vintage-brown uppercase tracking-widest text-xs mb-1">Lokasi</p>
            <p className="serif-text text-base leading-relaxed text-vintage-brown weathered-text">{location}</p>
          </div>
        </div>
      </div>

      <div className="mt-12 pt-10 border-t border-vintage-gold/20 flex items-center gap-4">
        <div className="w-2 h-2 bg-vintage-gold rounded-full opacity-50"></div>
        <div className="flex-1">
          <p className="serif-text text-[10px] uppercase tracking-[0.3em] text-vintage-brown/60 mb-1">Dress Code:</p>
          <p className="serif-text text-sm italic text-vintage-brown-dark weathered-text">Busana batik dan bersepatu.</p>
        </div>
      </div>

      <motion.a
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        href={gmapsLink}
        target="_blank"
        rel="noopener noreferrer"
        className="mt-10 flex items-center justify-center gap-3 bg-vintage-brown text-vintage-cream py-5 rounded-2xl shadow-xl hover:bg-vintage-gold transition-all group overflow-hidden relative"
      >
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/old-paper.png')] opacity-10"></div>
        <ExternalLink size={20} className="group-hover:rotate-12 transition-transform" />
        <span className="serif-text font-bold text-sm tracking-[0.2em] uppercase">Buka Google Maps</span>
      </motion.a>
    </motion.div>
  );

  return (
    <section id="acara" className="py-24 relative overflow-hidden bg-vintage-ivory/50">
      <TornEdge position="top" />
      
      <div className="container mx-auto px-6 relative z-10 pt-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-20"
        >
          <h2 className="script-text text-7xl text-vintage-brown gold-glow">Momen Bahagia</h2>
          <div className="h-[1.5px] w-32 bg-gradient-to-r from-transparent via-vintage-gold/50 to-transparent mx-auto mt-6"></div>
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-12 max-w-6xl mx-auto">
          <Card
            title="Akad Nikah"
            date="Rabu, 15 Maret 2027"
            time="10.00 WIB — Selesai"
            location="RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur 76281"
            gmapsLink="https://maps.google.com/?q=RT+02,+Desa+Padang+Jaya,+Kec.+Kuaro,+Kab.+Paser"
          />
          <Card
            title="Resepsi"
            date="Rabu, 15 Maret 2027"
            time="13.00 WIB — Selesai"
            location="RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur 76281"
            gmapsLink="https://maps.google.com/?q=RT+02,+Desa+Padang+Jaya,+Kec.+Kuaro,+Kab.+Paser"
          />
        </div>

        {/* Dummy Map Embed Placeholder */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-20 rounded-3xl overflow-hidden shadow-2xl border-4 border-white/50 grayscale-[50%] hover:grayscale-0 transition-all duration-700 h-[400px] relative"
        >
          <iframe 
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15951.68351543169!2d116.0371!3d-1.8974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMcKwNTMnNTAuNiJTIDExNsKwMDInMTMuNiJF!5e0!3m2!1sid!2sid!4v1620000000000!5m2!1sid!2sid" 
            width="100%" 
            height="100%" 
            style={{ border: 0 }} 
            allowFullScreen 
            loading="lazy"
          ></iframe>
        </motion.div>
      </div>

      {/* Corner Ornaments */}
      <VintageOrnament className="absolute top-10 left-10 w-48 h-48 opacity-10 pointer-events-none rotate-180" />
      <VintageOrnament className="absolute bottom-10 right-10 w-48 h-48 opacity-10 pointer-events-none" />
    </section>
  );
};

export default EventDetails;

// public/templates/Template 9/src/components/EventDetails.vue
<template>
  <section id="lokasi" class="py-20 px-6 bg-neo-white grid-bg border-b-6 border-neo-black">
    <div class="max-w-6xl mx-auto">
      <div class="flex flex-col md:flex-row gap-12">
        <!-- Akad Nikah Card -->
        <div class="flex-1 bg-neo-white neo-border-4 neo-shadow-lg p-8 md:p-12 relative overflow-hidden group">
          <!-- Decorative Background Text -->
          <div class="absolute -top-10 -right-10 text-9xl font-black text-neo-black opacity-5 pointer-events-none group-hover:opacity-10 transition-opacity">AKAD</div>
          
          <div class="relative z-10">
            <div class="section-label mb-6 bg-neo-blue text-neo-white">Akad Nikah</div>
            <h3 class="text-4xl md:text-5xl font-black uppercase mb-8">Informasi Acara</h3>
            
            <div class="space-y-6">
              <div class="flex gap-4">
                <div class="w-12 h-12 bg-neo-black text-neo-yellow flex items-center justify-center shrink-0 neo-border">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
                </div>
                <div>
                  <p class="text-xs font-black uppercase opacity-60">Hari & Tanggal</p>
                  <p class="text-xl font-black">Rabu, 15 Maret 2027</p>
                </div>
              </div>

              <div class="flex gap-4">
                <div class="w-12 h-12 bg-neo-blue text-neo-white flex items-center justify-center shrink-0 neo-border">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                </div>
                <div>
                  <p class="text-xs font-black uppercase opacity-60">Waktu</p>
                  <p class="text-xl font-black">10.00 WIB — Selesai</p>
                </div>
              </div>

              <div class="flex gap-4">
                <div class="w-12 h-12 bg-neo-red text-neo-white flex items-center justify-center shrink-0 neo-border">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                </div>
                <div>
                  <p class="text-xs font-black uppercase opacity-60">Lokasi</p>
                  <p class="text-lg font-bold leading-tight">RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur 76281</p>
                </div>
              </div>

              <div class="bg-neo-black text-neo-white p-4 neo-shadow-blue mt-8">
                <p class="text-xs font-black uppercase text-neo-blue mb-1">Dress Code</p>
                <p class="font-bold">Busana batik dan bersepatu.</p>
              </div>

              <a 
                href="https://maps.app.goo.gl/uX7m1sWpW4z9rWz6A" 
                target="_blank" 
                class="neo-btn neo-btn-blue w-full flex items-center justify-center gap-3 mt-4"
              >
                GOOGLE MAPS
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h6v6"></path><path d="M10 14L21 3"></path><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path></svg>
              </a>
            </div>
          </div>
        </div>

        <!-- Resepsi Card -->
        <div class="flex-1 bg-neo-white neo-border-4 neo-shadow-lg p-8 md:p-12 relative overflow-hidden group">
          <!-- Decorative Background Text -->
          <div class="absolute -top-10 -right-10 text-9xl font-black text-neo-black opacity-5 pointer-events-none group-hover:opacity-10 transition-opacity">RESEPSI</div>
          
          <div class="relative z-10">
            <div class="section-label mb-6 bg-neo-red text-neo-white">Resepsi</div>
            <h3 class="text-4xl md:text-5xl font-black uppercase mb-8">Informasi Acara</h3>
            
            <div class="space-y-6">
              <div class="flex gap-4">
                <div class="w-12 h-12 bg-neo-black text-neo-yellow flex items-center justify-center shrink-0 neo-border">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
                </div>
                <div>
                  <p class="text-xs font-black uppercase opacity-60">Hari & Tanggal</p>
                  <p class="text-xl font-black">Rabu, 15 Maret 2027</p>
                </div>
              </div>

              <div class="flex gap-4">
                <div class="w-12 h-12 bg-neo-red text-neo-white flex items-center justify-center shrink-0 neo-border">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                </div>
                <div>
                  <p class="text-xs font-black uppercase opacity-60">Waktu</p>
                  <p class="text-xl font-black">13.00 WIB — Selesai</p>
                </div>
              </div>

              <div class="flex gap-4">
                <div class="w-12 h-12 bg-neo-blue text-neo-white flex items-center justify-center shrink-0 neo-border">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                </div>
                <div>
                  <p class="text-xs font-black uppercase opacity-60">Lokasi</p>
                  <p class="text-lg font-bold leading-tight">RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur 76281</p>
                </div>
              </div>

              <div class="bg-neo-black text-neo-white p-4 neo-shadow-red mt-8">
                <p class="text-xs font-black uppercase text-neo-red mb-1">Dress Code</p>
                <p class="font-bold">Busana batik dan bersepatu.</p>
              </div>

              <a 
                href="https://maps.app.goo.gl/uX7m1sWpW4z9rWz6A" 
                target="_blank" 
                class="neo-btn neo-btn-red w-full flex items-center justify-center gap-3 mt-4"
              >
                GOOGLE MAPS
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h6v6"></path><path d="M10 14L21 3"></path><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path></svg>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
</script>

<style scoped>
</style>
