// public/templates/Template 6/src/components/Gallery.tsx
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import { weddingData } from "@/lib/constants";
import { X } from "lucide-react";

export default function Gallery() {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);

  return (
    <section className="py-24 bg-white">
      <div className="container mx-auto px-6 max-w-6xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <span className="font-sans text-xs tracking-[0.4em] uppercase font-bold text-gold/60 mb-4 block">Our Memories</span>
          <h2 className="text-4xl md:text-5xl font-serif text-accent">Gallery Our Moment</h2>
        </motion.div>

        <div className="columns-2 md:columns-3 gap-4 space-y-4">
          {weddingData.gallery.map((item, idx) => (
            <div key={idx} className="break-inside-avoid mb-4">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: idx % 3 * 0.1 }}
                onClick={() => setSelectedImage(item.src)}
                className="relative rounded-2xl overflow-hidden cursor-pointer group shadow-soft bg-beige/5"
              >
                <img
                  src={item.src}
                  alt={item.alt}
                  className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-110"
                  loading="lazy"
                />
              
                {/* Overlay on hover */}
                <div className="absolute inset-0 bg-accent/40 opacity-0 group-hover:opacity-100 transition-all duration-500 flex items-center justify-center backdrop-blur-[2px]">
                  <div className="bg-white/90 text-accent px-6 py-2 rounded-full text-[10px] font-bold uppercase tracking-widest">
                    Lihat Foto
                  </div>
                </div>

                {/* Decorative Border on hover */}
                <div className="absolute inset-3 border border-white/20 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />
              </motion.div>
            </div>
          ))}
        </div>
      </div>

      {/* Lightbox */}
      <AnimatePresence>
        {selectedImage && (
          <motion.div
            initial={{ opacity: 0, backdropFilter: "blur(0px)" }}
            animate={{ opacity: 1, backdropFilter: "blur(10px)" }}
            exit={{ opacity: 0, backdropFilter: "blur(0px)" }}
            className="fixed inset-0 z-[200] bg-black/90 flex items-center justify-center p-4"
            onClick={() => setSelectedImage(null)}
          >
            <button 
              className="absolute top-6 right-6 z-[210] text-white/70 hover:text-white transition-colors p-2"
              onClick={() => setSelectedImage(null)}
            >
              <X className="h-8 w-8" />
            </button>

            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="relative w-full max-w-5xl h-full flex items-center justify-center"
            >
              <img
                src={selectedImage}
                alt="Selected"
                className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
              />
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}

// public/templates/Template 9/src/components/Gallery.vue
<template>
  <section id="galeri" class="py-20 px-6 bg-neo-white grid-bg border-b-6 border-neo-black overflow-hidden">
    <div class="max-w-6xl mx-auto">
      <div class="mb-20 flex flex-col md:flex-row items-end justify-between gap-8">
        <div class="transform -rotate-1">
          <h2 class="section-label mb-4 bg-neo-black text-neo-red">Our Memories</h2>
          <h3 class="text-[clamp(2rem,10vw,4.5rem)] font-black uppercase tracking-tighter leading-[0.8]">
            GALLERY <br /> <span class="text-neo-red">OUR</span> <span class="text-neo-blue">MOMENT</span>
          </h3>
        </div>
        <div class="hidden md:block bg-neo-yellow neo-border-4 p-4 neo-shadow rotate-2 font-black text-xl">
          NO FILTERS. <br /> JUST BRUTAL.
        </div>
      </div>

      <!-- Brutal Asymmetrical Grid -->
      <div ref="galleryRef" class="grid grid-cols-2 md:grid-cols-4 gap-6 md:gap-10 mt-12 group/grid">
        <div 
          v-for="(img, index) in images" 
          :key="index"
          class="gallery-item-brutal relative group cursor-pointer neo-border-4 neo-shadow-lg transform transition-all duration-700 hover:-translate-y-2 hover:scale-[1.05] group-hover/grid:blur-sm group-hover/grid:opacity-50 hover:!blur-none hover:!opacity-100 active:scale-95"
          :class="[
            img.class, 
            img.bg,
            isVisible ? 'opacity-100 translate-y-0 scale-100' : 'opacity-0 translate-y-16 scale-90 pointer-events-none'
          ]"
          :style="isVisible && !animationDone ? { transitionDelay: `${index * 100}ms` } : {}"
          @click="openLightbox(index)"
        >
          <!-- Brutalist Tape -->
          <div class="absolute -top-3 left-1/2 -translate-x-1/2 w-16 h-6 bg-neo-black z-20" :class="index % 2 === 0 ? '-rotate-3' : 'rotate-2'"></div>
          
          <!-- Frame Padding -->
          <div class="p-3 md:p-4 h-full flex flex-col">
            <div class="w-full h-full relative overflow-hidden neo-border-4 border-neo-black bg-neo-white">
              <img 
                :src="img.src" 
                :alt="img.alt" 
                loading="lazy"
                class="w-full h-full object-cover transition-all duration-500 transform group-hover:scale-110" 
              />
              <!-- Hover Overlay -->
              <div class="absolute inset-0 bg-neo-black opacity-0 group-hover:opacity-20 transition-opacity mix-blend-multiply"></div>
            </div>
          </div>
        </div>
      </div>

      <!-- Custom Lightbox -->
      <div v-if="lightboxOpen" class="fixed inset-0 z-[9999] flex items-center justify-center bg-neo-black/95 p-4 animate-pop-in">
        <button @click="lightboxOpen = false" class="absolute top-6 right-6 neo-btn neo-btn-red text-neo-white z-[10000]">
          CLOSE [X]
        </button>
        
        <div class="relative w-full max-w-5xl flex flex-col items-center">
          <div class="relative neo-border-4 border-neo-white bg-neo-black overflow-hidden max-h-[85vh] p-2 md:p-4 transform rotate-1">
            <img :src="images[currentIndex].src" :alt="images[currentIndex].alt" class="max-w-full max-h-[80vh] object-contain neo-border-2 border-neo-white" />
            
            <!-- Floating Navigation -->
            <button @click.stop="prev" class="absolute left-2 top-1/2 -translate-y-1/2 neo-btn neo-btn-blue p-3 !shadow-neo-white transform -translate-x-1/2 hover:scale-110"><-</button>
            <button @click.stop="next" class="absolute right-2 top-1/2 -translate-y-1/2 neo-btn neo-btn-red p-3 !shadow-neo-white transform translate-x-1/2 hover:scale-110">-></button>
          </div>
          
          <div class="mt-8 bg-neo-white text-neo-black font-black px-8 py-3 neo-border-4 text-2xl uppercase tracking-widest shadow-[8px_8px_0px_var(--neo-blue)] transform -rotate-2">
            Photo {{ currentIndex + 1 }} / {{ images.length }}
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const images = [
  { src: '/assets/Image/gallery1.jpg', alt: 'Gallery 1', class: 'col-span-2 row-span-2 transform -rotate-1', bg: 'bg-neo-yellow' },
  { src: '/assets/Image/gallery4.jpg', alt: 'Gallery 2', class: 'col-span-2 aspect-video transform rotate-2', bg: 'bg-neo-blue' },
  { src: '/assets/Image/pria.jpg', alt: 'Fanny Photo', class: 'col-span-1 aspect-square transform md:rotate-3', bg: 'bg-neo-red' },
  { src: '/assets/Image/wanita.jpg', alt: 'Claude Photo', class: 'col-span-1 aspect-square transform md:-rotate-2', bg: 'bg-neo-yellow' },
  { src: '/assets/Image/gallery6.jpg', alt: 'Slider 3', class: 'col-span-2 aspect-video transform -rotate-1', bg: 'bg-neo-red' },
  { src: '/assets/Image/gallery3.webp', alt: 'Background Photo', class: 'col-span-2 md:col-span-1 aspect-square transform rotate-2', bg: 'bg-neo-blue' }
]

const lightboxOpen = ref(false)
const currentIndex = ref(0)

const galleryRef = ref(null)
const isVisible = ref(false)
const animationDone = ref(false)
let observer = null

onMounted(() => {
  observer = new IntersectionObserver((entries) => {
    if (entries[0].isIntersecting) {
      isVisible.value = true
      // Tunggu hingga semua item selesai beranimasi (durasi + max stagger delay)
      setTimeout(() => {
        animationDone.value = true
      }, 1500)
      observer.disconnect()
    }
  }, { threshold: 0.1 })

  if (galleryRef.value) {
    observer.observe(galleryRef.value)
  }
})

onUnmounted(() => {
  if (observer) observer.disconnect()
})

function openLightbox(index) {
  currentIndex.value = index
  lightboxOpen.value = true
}

function next() {
  currentIndex.value = (currentIndex.value + 1) % images.length
}

function prev() {
  currentIndex.value = (currentIndex.value - 1 + images.length) % images.length
}
</script>

<style scoped>
.gallery-item-brutal {
  box-shadow: 8px 8px 0px var(--border-main);
}
.gallery-item-brutal:hover {
  z-index: 50;
  box-shadow: 16px 16px 0px var(--border-main);
}
</style>
