// public/templates/Template 6/src/components/RSVP.tsx
"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Send, MessageSquare, Quote } from "lucide-react";
import { weddingData } from "@/lib/constants";

interface Message {
  name: string;
  text: string;
  date: string;
}

export default function RSVP() {
  const [name, setName] = useState("");
  const [presence, setPresence] = useState("Hadir");
  const [message, setMessage] = useState("");
  const [wishes, setWishes] = useState<Message[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    // Basic local storage to persist wishes for the demo
    const savedWishes = localStorage.getItem("wedding_wishes");
    if (savedWishes) {
      setWishes(JSON.parse(savedWishes));
    }
  }, []);

  const handleSubmitPresence = (e: React.FormEvent) => {
    e.preventDefault();
    const text = `Halo Blacky & Cimeng, Saya ${name} memberikan konfirmasi bahwa saya ${presence} di acara pernikahan kalian. Terima kasih!`;
    const url = `https://wa.me/${weddingData.contact.whatsapp}?text=${encodeURIComponent(text)}`;
    window.open(url, "_blank");
  };

  const handleSubmitWish = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !message) return;

    setIsSubmitting(true);
    
    // Simulate API call
    setTimeout(() => {
      const newWish: Message = {
        name,
        text: message,
        date: new Date().toLocaleDateString("id-ID", { 
          day: "numeric", 
          month: "long", 
          year: "numeric",
          hour: "2-digit",
          minute: "2-digit"
        }),
      };

      const updatedWishes = [newWish, ...wishes];
      setWishes(updatedWishes);
      localStorage.setItem("wedding_wishes", JSON.stringify(updatedWishes));
      
      setName("");
      setMessage("");
      setIsSubmitting(false);
    }, 800);
  };

  return (
    <section className="py-24 bg-white">
      <div className="container mx-auto px-6 max-w-5xl">
        <div className="grid lg:grid-cols-2 gap-16">
          {/* Presence Form */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="bg-beige/10 p-10 rounded-[2.5rem] border border-gold/10 shadow-soft"
          >
            <div className="flex items-center gap-4 mb-8">
              <div className="h-12 w-12 rounded-full bg-gold/10 flex items-center justify-center">
                <Send className="h-6 w-6 text-gold" />
              </div>
              <h3 className="text-3xl font-serif text-accent">RSVP</h3>
            </div>
            
            <p className="text-sm text-accent/70 mb-8 leading-relaxed">
              Merupakan suatu kehormatan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.
            </p>

            <form onSubmit={handleSubmitPresence} className="space-y-6">
              <div>
                <label className="block text-xs font-bold uppercase tracking-widest text-accent/60 mb-2 ml-1">Nama</label>
                <input
                  type="text"
                  required
                  placeholder="Nama Lengkap"
                  className="w-full bg-white border border-gold/10 focus:border-gold/50 rounded-2xl p-4 text-sm outline-none transition-all shadow-sm"
                  onChange={(e) => setName(e.target.value)}
                />
              </div>

              <div>
                <label className="block text-xs font-bold uppercase tracking-widest text-accent/60 mb-2 ml-1">Konfirmasi Kehadiran</label>
                <select
                  className="w-full bg-white border border-gold/10 focus:border-gold/50 rounded-2xl p-4 text-sm outline-none transition-all shadow-sm appearance-none"
                  onChange={(e) => setPresence(e.target.value)}
                >
                  <option value="Hadir">Hadir</option>
                  <option value="Tidak Hadir">Tidak Hadir</option>
                  <option value="Masih Ragu">Masih Ragu</option>
                </select>
              </div>

              <button
                type="submit"
                className="w-full bg-gold hover:bg-gold/90 text-white font-bold tracking-[0.2em] uppercase text-xs py-5 rounded-2xl shadow-lg shadow-gold/20 transition-all flex items-center justify-center gap-3"
              >
                Kirim via WhatsApp
              </button>
            </form>
          </motion.div>

          {/* Wishes Form */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="flex flex-col"
          >
            <div className="bg-accent/5 p-10 rounded-[2.5rem] border border-accent/5 mb-8">
                <div className="flex items-center gap-4 mb-6">
                    <div className="h-12 w-12 rounded-full bg-accent/5 flex items-center justify-center">
                        <MessageSquare className="h-6 w-6 text-accent/60" />
                    </div>
                    <h3 className="text-3xl font-serif text-accent">Doa & Ucapan</h3>
                </div>

                <form onSubmit={handleSubmitWish} className="space-y-5">
                    <input
                        type="text"
                        required
                        value={name}
                        placeholder="Nama Anda"
                        className="w-full bg-white border border-gold/10 focus:border-gold/50 rounded-2xl p-4 text-sm outline-none transition-all"
                        onChange={(e) => setName(e.target.value)}
                    />
                    <textarea
                        required
                        value={message}
                        rows={4}
                        placeholder="Tulis doa dan ucapan terbaik..."
                        className="w-full bg-white border border-gold/10 focus:border-gold/50 rounded-2xl p-4 text-sm outline-none transition-all resize-none"
                        onChange={(e) => setMessage(e.target.value)}
                    />
                    <button
                        type="submit"
                        disabled={isSubmitting}
                        className="w-full bg-accent text-white font-bold tracking-[0.2em] uppercase text-xs py-5 rounded-2xl shadow-lg transition-all flex items-center justify-center gap-3"
                    >
                        {isSubmitting ? "Mengirim..." : "Kirim Ucapan"}
                    </button>
                </form>
            </div>

            {/* Wishes List */}
            <div className="flex-1 max-h-[400px] overflow-y-auto px-2 space-y-4 custom-scrollbar">
                <AnimatePresence initial={false}>
                    {wishes.map((wish, idx) => (
                        <motion.div
                            key={idx + wish.name}
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="bg-white p-6 rounded-2xl shadow-sm border border-gold/5 relative overflow-hidden group"
                        >
                            <Quote className="absolute -right-2 -bottom-2 h-16 w-16 text-gold/5 group-hover:text-gold/10 transition-colors" />
                            <h4 className="font-serif text-gold text-lg mb-1">{wish.name}</h4>
                            <p className="text-xs text-accent/40 mb-3 uppercase tracking-tighter">{wish.date}</p>
                            <p className="text-sm text-accent/70 leading-relaxed relative z-10">{wish.text}</p>
                        </motion.div>
                    ))}
                </AnimatePresence>
                {wishes.length === 0 && (
                    <div className="text-center py-10 opacity-30 text-sm italic">Belum ada ucapan...</div>
                )}
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

// public/templates/Template 9/src/components/RSVP.vue
<template>
  <section id="rsvp" class="py-20 px-6 bg-neo-white grid-bg border-b-8 border-neo-black relative overflow-hidden">
    <div class="absolute inset-0 bg-gradient-to-b from-transparent to-[var(--bg-main)] opacity-50 z-0"></div>
    
    <div class="max-w-3xl mx-auto">
      <div class="mb-16 text-center transform rotate-[1deg] relative z-10">
        <h2 class="section-label mb-4 bg-neo-red text-neo-white">RSVP</h2>
        <h3 class="section-title">Konfirmasi Kehadiran</h3>
        <p class="font-bold mt-4 max-w-lg mx-auto text-neo-black">
          Merupakan suatu kehormatan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.
        </p>
      </div>

      <div class="bg-neo-white text-neo-black neo-border-4 neo-shadow-lg p-8 md:p-12 relative z-10">
        <!-- Floating label -->
        <div class="absolute -top-6 -right-6 bg-neo-red text-neo-white px-6 py-2 font-black text-xl neo-border rotate-3">
          DAFTAR HADIR
        </div>

        <form @submit.prevent="sendRSVP" class="space-y-6">
          <div class="space-y-2">
            <label class="block text-sm font-black uppercase tracking-widest">Nama Lengkap</label>
            <input 
              v-model="form.nama" 
              type="text" 
              placeholder="Masukkan Nama Anda" 
              required 
              class="neo-input"
            />
          </div>

          <div class="space-y-2">
            <label class="block text-sm font-black uppercase tracking-widest">Konfirmasi Kehadiran</label>
            <select v-model="form.status" required class="neo-input">
              <option value="" disabled>Pilih Status Kehadiran</option>
              <option value="Hadir">Hadir</option>
              <option value="Tidak Hadir">Tidak Hadir</option>
            </select>
          </div>

          <div class="space-y-2" v-if="form.status === 'Hadir'">
            <label class="block text-sm font-black uppercase tracking-widest">Jumlah Tamu</label>
            <select v-model="form.jumlah" class="neo-input">
              <option value="1">1 Orang</option>
              <option value="2">2 Orang</option>
            </select>
          </div>

          <div class="pt-4">
            <button 
              type="submit" 
              class="neo-btn neo-btn-black w-full flex items-center justify-center gap-3 text-lg py-4"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12.031 6.172c-3.181 0-5.767 2.586-5.767 5.768 0 3.18 2.586 5.767 5.767 5.767 3.18 0 5.768-2.587 5.768-5.767 0-3.182-2.588-5.768-5.768-5.768zm0 9.44c-2.024 0-3.671-1.647-3.671-3.672 0-2.023 1.647-3.671 3.671-3.671 2.025 0 3.672 1.648 3.672 3.671 0 2.025-1.647 3.672-3.672 3.672z"/><path d="M12.031 3C1.439 3 1.439 12.03 1.439 12.03c0 9.03 10.592 9.03 10.592 9.03s10.592 0 10.592-9.03c0-9.03-10.592-9.03-10.592-9.03zm0 15.65c-6.108 0-6.108-6.62-6.108-6.62 0-6.621 6.108-6.621 6.108-6.621s6.108 0 6.108 6.621c0 6.62-6.108 6.62-6.108 6.62z"/></svg>
              KIRIM VIA WHATSAPP
            </button>
          </div>
        </form>
      </div>

      <!-- Ucapan Section -->
      <div class="mt-20 relative z-10">
        <div class="text-center mb-8">
          <h3 class="text-3xl font-black uppercase tracking-tight">Doa & Ucapan</h3>
        </div>
        
        <div class="bg-neo-white neo-border-4 neo-shadow p-8">
          <div class="space-y-4">
            <input v-model="newUcapan.nama" type="text" placeholder="Nama Anda" class="neo-input" />
            <textarea v-model="newUcapan.pesan" placeholder="Tulis doa dan ucapan terbaik..." rows="4" class="neo-input"></textarea>
            <button @click="addUcapan" class="neo-btn neo-btn-red w-full !text-white">KIRIM UCAPAN</button>
          </div>

          <div class="mt-12 space-y-4 max-h-[400px] overflow-y-auto pr-4 custom-scroll">
            <div v-if="ucapans.length === 0" class="text-center py-8 border-2 border-dashed border-neo-yellow/30 opacity-50">
              Belum ada ucapan...
            </div>
            <div v-for="(u, index) in ucapans" :key="index" class="bg-neo-white text-neo-black p-4 neo-border-4 neo-shadow mb-4">
              <p class="text-sm font-black uppercase text-neo-blue mb-1">{{ u.nama }}</p>
              <p class="font-bold leading-relaxed">{{ u.pesan }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  guestName: { type: String, default: '' }
})

const form = ref({
  nama: props.guestName,
  status: '',
  jumlah: '1'
})

const ucapans = ref([])
const newUcapan = ref({
  nama: props.guestName,
  pesan: ''
})

function sendRSVP() {
  const message = `Halo Claude & Fanny, saya ${form.value.nama} mengonfirmasi ${form.value.status} ${form.value.status === 'Hadir' ? `dengan ${form.value.jumlah} orang` : ''}. Terima kasih!`
  const url = `https://wa.me/082229243737?text=${encodeURIComponent(message)}`
  window.open(url, '_blank')
}

function addUcapan() {
  if (!newUcapan.value.nama || !newUcapan.value.pesan) return
  ucapans.value.unshift({ ...newUcapan.value })
  newUcapan.value.pesan = ''
}
</script>

<style scoped>
.custom-scroll::-webkit-scrollbar { width: 4px; }
.custom-scroll::-webkit-scrollbar-track { background: transparent; }
.custom-scroll::-webkit-scrollbar-thumb { background: var(--neo-yellow); }
</style>
