// public/templates/Template 7/src/components/MusicPlayer.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Music, Pause, Disc } from 'lucide-vue-next'

const audioRef = ref<HTMLAudioElement | null>(null)
const isPlaying = ref(false)

const playMusic = () => {
  if (audioRef.value && !isPlaying.value) {
    audioRef.value.play().then(() => {
      isPlaying.value = true
    }).catch(e => console.log('Autoplay blocked', e))
  }
}

defineExpose({
  playMusic
})

const togglePlay = () => {
  if (audioRef.value) {
    if (isPlaying.value) {
      audioRef.value.pause()
    } else {
      audioRef.value.play()
    }
    isPlaying.value = !isPlaying.value
  }
}

const handleVisibilityChange = () => {
  if (document.hidden && isPlaying.value) {
    audioRef.value?.pause()
    isPlaying.value = false
  }
}

onMounted(() => {
  document.addEventListener('visibilitychange', handleVisibilityChange)
})

onUnmounted(() => {
  if (audioRef.value) {
    audioRef.value.pause()
  }
  document.removeEventListener('visibilitychange', handleVisibilityChange)
})
</script>

<template>
  <div class="fixed z-[100] bottom-24 md:bottom-10 right-6 md:right-10 flex flex-col items-center gap-4">
    <!-- Pulsing Ring -->
    <div v-show="isPlaying" class="absolute inset-0 rounded-full bg-rose-gold/20 animate-ping -z-10"></div>
    
    <button 
      @click="togglePlay" 
      class="w-12 h-12 md:w-14 md:h-14 flex items-center justify-center rounded-full glass border border-white/50 shadow-2xl text-rose-gold hover:scale-110 active:scale-95 transition-all group overflow-hidden"
    >
      <div v-if="isPlaying" class="relative">
        <Disc class="w-6 h-6 md:w-7 md:h-7 animate-spin-slow" />
        <div class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
          <Pause class="w-4 h-4 text-rose-gold fill-current" />
        </div>
      </div>
      <Music v-else class="w-6 h-6 md:w-7 md:h-7" />
      
      <!-- Inner Glow -->
      <div class="absolute inset-0 bg-gradient-to-tr from-white/30 to-transparent pointer-events-none"></div>
    </button>

    <audio ref="audioRef" src="/assets/audio/background-music.mp3" loop preload="auto"></audio>
  </div>
</template>

<style scoped>
.animate-spin-slow {
  animation: spin 5s linear infinite;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.glass {
  background: rgba(255, 255, 255, 0.6);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
}
</style>

// public/templates/Template 15/src/components/MusicPlayer.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { Music, Music2 } from "lucide-react/dist/cjs/lucide-react.js";
import { motion, AnimatePresence } from "framer-motion";

export default function MusicPlayer({ isPlaying: initialPlaying = false }) {
  const [isPlaying, setIsPlaying] = useState(initialPlaying);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  useEffect(() => {
    if (initialPlaying) {
      setIsPlaying(true);
      if (audioRef.current) {
        audioRef.current.play().catch(err => console.log("Auto-play blocked"));
      }
    }

    const handleVisibilityChange = () => {
      if (document.hidden) {
        if (audioRef.current && !audioRef.current.paused) {
          audioRef.current.pause();
          setIsPlaying(false);
        }
      } else {
        if (initialPlaying && audioRef.current && audioRef.current.paused) {
          audioRef.current.play().catch(() => {});
          setIsPlaying(true);
        }
      }
    };

    document.addEventListener("visibilitychange", handleVisibilityChange);
    return () => document.removeEventListener("visibilitychange", handleVisibilityChange);
  }, [initialPlaying]);

  const togglePlay = () => {
    if (audioRef.current) {
      if (isPlaying) {
        audioRef.current.pause();
      } else {
        audioRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  return (
    <div className="fixed bottom-28 right-6 z-[90]">
      <audio ref={audioRef} loop src="/assets/audio/background-music.mp3" />
      
      <motion.button
        whileHover={{ scale: 1.1 }}
        whileTap={{ scale: 0.9 }}
        onClick={togglePlay}
        className={`w-14 h-14 rounded-full flex items-center justify-center shadow-2xl transition-all duration-500 ${
          isPlaying ? "bg-neon-pink text-white animate-spin-slow" : "bg-white text-gray-400"
        }`}
      >
        <AnimatePresence mode="wait">
          {isPlaying ? (
            <motion.div
              key="playing"
              initial={{ opacity: 0, rotate: -180 }}
              animate={{ opacity: 1, rotate: 0 }}
              exit={{ opacity: 0, rotate: 180 }}
            >
              <Music2 size={24} />
            </motion.div>
          ) : (
            <motion.div
              key="paused"
              initial={{ opacity: 0, rotate: 180 }}
              animate={{ opacity: 1, rotate: 0 }}
              exit={{ opacity: 0, rotate: -180 }}
            >
              <Music size={24} />
            </motion.div>
          )}
        </AnimatePresence>
      </motion.button>

      {/* Floating Notes when playing */}
      {isPlaying && (
        <div className="absolute -top-10 left-1/2 -translate-x-1/2 pointer-events-none">
          {[...Array(3)].map((_, i) => (
            <motion.span
              key={i}
              initial={{ opacity: 0, y: 0, x: 0 }}
              animate={{ opacity: [0, 1, 0], y: -50, x: (i - 1) * 20 }}
              transition={{ 
                duration: 2, 
                repeat: Infinity, 
                delay: i * 0.5,
                ease: "easeOut"
              }}
              className="absolute text-neon-pink text-xl"
            >
              <Music size={16} />
            </motion.span>
          ))}
        </div>
      )}

      <style jsx global>{`
        @keyframes spin-slow {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        .animate-spin-slow {
          animation: spin-slow 8s linear infinite;
        }
      `}</style>
    </div>
  );
}
