// public/templates/Template 9/src/components/RSVP.vue
<template>
  <section id="rsvp" class="py-20 px-6 bg-neo-white grid-bg border-b-8 border-neo-black relative overflow-hidden">
    <div class="absolute inset-0 bg-gradient-to-b from-transparent to-[var(--bg-main)] opacity-50 z-0"></div>
    
    <div class="max-w-3xl mx-auto">
      <div class="mb-16 text-center transform rotate-[1deg] relative z-10">
        <h2 class="section-label mb-4 bg-neo-red text-neo-white">RSVP</h2>
        <h3 class="section-title">Konfirmasi Kehadiran</h3>
        <p class="font-bold mt-4 max-w-lg mx-auto text-neo-black">
          Merupakan suatu kehormatan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.
        </p>
      </div>

      <div class="bg-neo-white text-neo-black neo-border-4 neo-shadow-lg p-8 md:p-12 relative z-10">
        <!-- Floating label -->
        <div class="absolute -top-6 -right-6 bg-neo-red text-neo-white px-6 py-2 font-black text-xl neo-border rotate-3">
          DAFTAR HADIR
        </div>

        <form @submit.prevent="sendRSVP" class="space-y-6">
          <div class="space-y-2">
            <label class="block text-sm font-black uppercase tracking-widest">Nama Lengkap</label>
            <input 
              v-model="form.nama" 
              type="text" 
              placeholder="Masukkan Nama Anda" 
              required 
              class="neo-input"
            />
          </div>

          <div class="space-y-2">
            <label class="block text-sm font-black uppercase tracking-widest">Konfirmasi Kehadiran</label>
            <select v-model="form.status" required class="neo-input">
              <option value="" disabled>Pilih Status Kehadiran</option>
              <option value="Hadir">Hadir</option>
              <option value="Tidak Hadir">Tidak Hadir</option>
            </select>
          </div>

          <div class="space-y-2" v-if="form.status === 'Hadir'">
            <label class="block text-sm font-black uppercase tracking-widest">Jumlah Tamu</label>
            <select v-model="form.jumlah" class="neo-input">
              <option value="1">1 Orang</option>
              <option value="2">2 Orang</option>
            </select>
          </div>

          <div class="pt-4">
            <button 
              type="submit" 
              class="neo-btn neo-btn-black w-full flex items-center justify-center gap-3 text-lg py-4"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12.031 6.172c-3.181 0-5.767 2.586-5.767 5.768 0 3.18 2.586 5.767 5.767 5.767 3.18 0 5.768-2.587 5.768-5.767 0-3.182-2.588-5.768-5.768-5.768zm0 9.44c-2.024 0-3.671-1.647-3.671-3.672 0-2.023 1.647-3.671 3.671-3.671 2.025 0 3.672 1.648 3.672 3.671 0 2.025-1.647 3.672-3.672 3.672z"/><path d="M12.031 3C1.439 3 1.439 12.03 1.439 12.03c0 9.03 10.592 9.03 10.592 9.03s10.592 0 10.592-9.03c0-9.03-10.592-9.03-10.592-9.03zm0 15.65c-6.108 0-6.108-6.62-6.108-6.62 0-6.621 6.108-6.621 6.108-6.621s6.108 0 6.108 6.621c0 6.62-6.108 6.62-6.108 6.62z"/></svg>
              KIRIM VIA WHATSAPP
            </button>
          </div>
        </form>
      </div>

      <!-- Ucapan Section -->
      <div class="mt-20 relative z-10">
        <div class="text-center mb-8">
          <h3 class="text-3xl font-black uppercase tracking-tight">Doa & Ucapan</h3>
        </div>
        
        <div class="bg-neo-white neo-border-4 neo-shadow p-8">
          <div class="space-y-4">
            <input v-model="newUcapan.nama" type="text" placeholder="Nama Anda" class="neo-input" />
            <textarea v-model="newUcapan.pesan" placeholder="Tulis doa dan ucapan terbaik..." rows="4" class="neo-input"></textarea>
            <button @click="addUcapan" class="neo-btn neo-btn-red w-full !text-white">KIRIM UCAPAN</button>
          </div>

          <div class="mt-12 space-y-4 max-h-[400px] overflow-y-auto pr-4 custom-scroll">
            <div v-if="ucapans.length === 0" class="text-center py-8 border-2 border-dashed border-neo-yellow/30 opacity-50">
              Belum ada ucapan...
            </div>
            <div v-for="(u, index) in ucapans" :key="index" class="bg-neo-white text-neo-black p-4 neo-border-4 neo-shadow mb-4">
              <p class="text-sm font-black uppercase text-neo-blue mb-1">{{ u.nama }}</p>
              <p class="font-bold leading-relaxed">{{ u.pesan }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  guestName: { type: String, default: '' }
})

const form = ref({
  nama: props.guestName,
  status: '',
  jumlah: '1'
})

const ucapans = ref([])
const newUcapan = ref({
  nama: props.guestName,
  pesan: ''
})

function sendRSVP() {
  const message = `Halo Claude & Fanny, saya ${form.value.nama} mengonfirmasi ${form.value.status} ${form.value.status === 'Hadir' ? `dengan ${form.value.jumlah} orang` : ''}. Terima kasih!`
  const url = `https://wa.me/082229243737?text=${encodeURIComponent(message)}`
  window.open(url, '_blank')
}

function addUcapan() {
  if (!newUcapan.value.nama || !newUcapan.value.pesan) return
  ucapans.value.unshift({ ...newUcapan.value })
  newUcapan.value.pesan = ''
}
</script>

<style scoped>
.custom-scroll::-webkit-scrollbar { width: 4px; }
.custom-scroll::-webkit-scrollbar-track { background: transparent; }
.custom-scroll::-webkit-scrollbar-thumb { background: var(--neo-yellow); }
</style>

// public/templates/Template 15/src/components/RSVP.tsx
"use client";

import { motion } from "framer-motion";
import { useState } from "react";
import { Send, CheckCircle2, Bell, Sparkles } from "lucide-react/dist/cjs/lucide-react.js";
import Image from "next/image";

export default function RSVP() {
  const [formData, setFormData] = useState({ name: "", status: "", guests: "1", message: "" });
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const whatsappMessage = `Halo Aditya & Lestari, saya ${formData.name} ingin mengonfirmasi kehadiran.\nStatus: ${formData.status === "yes" ? "Hadir" : "Tidak Hadir"}\nJumlah Tamu: ${formData.guests}\nPesan: ${formData.message}`;
    window.open(`https://wa.me/6282229243737?text=${encodeURIComponent(whatsappMessage)}`, "_blank");
    setSubmitted(true);
  };

  return (
    <section id="rsvp" className="py-24 px-4 sm:px-6 bg-white overflow-hidden">
      <div className="max-w-2xl mx-auto space-y-8">

        {/* Heading */}
        <div className="text-center space-y-2">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-2xl sm:text-3xl md:text-6xl font-heading font-bold text-gray-900 flex items-center justify-center gap-3"
          >
            <Bell size={26} className="text-soft-purple" /> RSVP
          </motion.h2>
          <p className="text-base text-gray-500 font-body">Konfirmasi kehadiran via WhatsApp</p>
        </div>

        {/* IG Notification Card + Form */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="bg-white border border-gray-200 rounded-2xl overflow-hidden shadow-xl"
        >
          {/* Notification Header */}
          <div className="px-4 py-3 border-b border-gray-100 flex items-center gap-3 bg-gray-50">
            <div className="relative">
              <div className="relative p-0.5 rounded-full bg-gradient-to-tr from-yellow-400 via-red-500 to-purple-600">
                <div className="bg-white p-0.5 rounded-full">
                  <div className="relative w-10 h-10 rounded-full overflow-hidden">
                    <Image src="/assets/Image/hero.jpg" alt="Profile" fill className="object-cover" />
                  </div>
                </div>
              </div>
              {/* Notif badge */}
              <div className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-red-500 rounded-full flex items-center justify-center">
                <span className="text-white text-[9px] font-black">1</span>
              </div>
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold text-gray-900 leading-tight">
                <span className="font-black">aditya_lestari_official</span> mengundang Anda ke pernikahan mereka.
              </p>
              <p className="text-xs text-gray-400 mt-0.5">Harap konfirmasi kehadiran · 15 Mar 2027</p>
            </div>
            <Bell size={18} className="text-gray-400 flex-shrink-0" />
          </div>

          {/* Form Area */}
          <div className="px-4 py-6">
            {submitted ? (
              <motion.div
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                className="text-center space-y-4 py-8"
              >
                <CheckCircle2 size={72} className="text-mint mx-auto" />
                <h3 className="text-2xl sm:text-3xl font-heading font-bold text-gray-800 flex items-center justify-center gap-2">
                  Terima Kasih! <Sparkles className="text-yellow-400 w-6 h-6" />
                </h3>
                <p className="text-base text-gray-600 font-body">Konfirmasi kehadiran Anda telah kami terima.</p>
                <button
                  onClick={() => setSubmitted(false)}
                  className="text-blue-500 font-bold text-sm hover:underline"
                >
                  Kirim Ulang
                </button>
              </motion.div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-4">

                {/* Name */}
                <div>
                  <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-1.5 ml-1">
                    Nama Lengkap
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="Masukkan nama Anda"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    className="w-full h-12 px-4 bg-gray-50 border border-gray-200 rounded-xl focus:border-soft-purple focus:outline-none text-sm font-body transition-all"
                  />
                </div>

                {/* Status */}
                <div>
                  <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-1.5 ml-1">
                    Konfirmasi Kehadiran
                  </label>
                  <div className="flex gap-3">
                    {[
                      { val: "yes", label: "Hadir" },
                      { val: "no", label: "Tidak Hadir" },
                    ].map((opt) => (
                      <button
                        key={opt.val}
                        type="button"
                        onClick={() => setFormData({ ...formData, status: opt.val })}
                        className={`flex-1 py-2.5 rounded-xl text-sm font-bold border transition-all ${
                          formData.status === opt.val
                            ? "bg-soft-purple text-white border-soft-purple shadow-md"
                            : "bg-gray-50 text-gray-700 border-gray-200"
                        }`}
                      >
                        {opt.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Guests */}
                <div>
                  <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-1.5 ml-1">
                    Jumlah Tamu
                  </label>
                  <div className="flex items-center gap-3">
                    {["1", "2", "3", "4", "5+"].map((n) => (
                      <button
                        key={n}
                        type="button"
                        onClick={() => setFormData({ ...formData, guests: n })}
                        className={`w-11 h-11 rounded-xl text-sm font-bold border transition-all ${
                          formData.guests === n
                            ? "bg-soft-purple text-white border-soft-purple shadow-md"
                            : "bg-gray-50 text-gray-700 border-gray-200"
                        }`}
                      >
                        {n}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Message */}
                <div>
                  <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-1.5 ml-1">
                    Pesan & Doa
                  </label>
                  <div className="relative">
                    <textarea
                      rows={3}
                      placeholder="Tulis doa dan ucapan terbaik..."
                      value={formData.message}
                      onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:border-soft-purple focus:outline-none text-sm font-body transition-all resize-none"
                    />
                  </div>
                </div>

                {/* Submit */}
                <motion.button
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  type="submit"
                  disabled={!formData.status}
                  className="w-full py-3 bg-green-500 text-white rounded-xl font-heading font-bold text-base flex items-center justify-center gap-3 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                >
                  <Send size={18} />
                  <span>Kirim via WhatsApp</span>
                </motion.button>

                <p className="text-center text-xs text-gray-400 font-bold uppercase tracking-widest">
                  Mohon konfirmasi sebelum 01 Des 2026
                </p>
              </form>
            )}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
