// public/templates/Template 7/src/components/OpeningScreen.vue
<script setup lang="ts">
import { MailOpen } from 'lucide-vue-next'
import { ref, onMounted } from 'vue'
import SakuraOrnament from './SakuraOrnament.vue'

defineEmits(['open'])

const guestName = ref('Tamu Undangan')

onMounted(() => {
  const urlParams = new URLSearchParams(window.location.search)
  const to = urlParams.get('to')
  if (to) {
    guestName.value = to.replace(/[-_]/g, ' ')
  }
})
</script>

<template>
  <div class="fixed inset-0 z-[100] overflow-y-auto bg-center bg-cover overflow-x-hidden" style="background-image: url('/assets/img/bg-new.webp');">
    <!-- Fixed background overlay (Optimized: no blur) -->
    <div class="fixed inset-0 bg-[#fff5f7]/85 pointer-events-none"></div>
    
    <!-- Decor Sakura Branch corner ornaments -->
    <SakuraOrnament position="top-right" class="w-64 h-64 md:w-96 md:h-96 opacity-60" />
    <SakuraOrnament position="bottom-left" class="w-64 h-64 md:w-96 md:h-96 opacity-40" />

    <!-- Content Container -->
    <div class="relative z-10 flex flex-col items-center justify-center min-h-[100vh] py-12 px-4 text-center w-full" data-aos="zoom-in">
      
      <!-- The Couple Photo -->
      <div class="relative mb-8 group shrink-0">
        <div class="absolute -inset-2 border-2 border-rose-gold/20 rounded-[100px] transform rotate-6 transition-transform group-hover:rotate-0 duration-1000"></div>
        <div class="w-40 h-40 md:w-48 md:h-48 rounded-[100px] border-[6px] border-white shadow-2xl overflow-hidden relative backdrop-blur-md">
           <img src="/assets/img/hero.webp" class="w-full h-full object-cover object-top transition-transform duration-700 group-hover:scale-110" />
        </div>
      </div>

      <div class="mb-6">
        <h1 class="text-4xl md:text-5xl lg:text-7xl font-serif text-rose-gold drop-shadow-xl text-shadow leading-tight">Razi & Seli</h1>
        <div class="section-divider mt-4 mb-2"></div>
        <h3 class="text-xs md:text-sm tracking-[0.4em] uppercase font-sans text-gray-500 font-bold">Undangan Pernikahan</h3>
      </div>
      
      <div class="mb-10 p-8 md:p-10 glass rounded-[40px] border border-white max-w-[90%] md:max-w-sm mx-auto shadow-2xl relative overflow-hidden shrink-0 group">
        <div class="absolute inset-0 bg-gradient-to-tr from-white/40 to-transparent pointer-events-none"></div>
        <div class="relative z-10">
          <p class="text-xs text-gray-400 mb-2 font-sans uppercase tracking-[0.2em] font-bold">Yth. Bapak / Ibu / Saudara/i</p>
          <p class="text-3xl md:text-4xl font-serif text-rose-gold mb-4 capitalize text-shadow">{{ guestName }}</p>
          <div class="section-divider w-12 mb-4"></div>
          <p class="text-xs md:text-sm font-sans font-light text-gray-600 leading-relaxed italic">Kami mengundang Anda untuk hadir di acara pernikahan kami.</p>
        </div>
      </div>
      
      <button @click="$emit('open')" class="flex items-center gap-3 px-10 py-4 text-white transition-all bg-rose-gold rounded-full shadow-2xl hover:bg-blush hover:shadow-rose-gold/40 hover:-translate-y-1 active:translate-y-0 group relative overflow-hidden shrink-0">
        <div class="absolute inset-0 bg-white/20 transform -translate-x-full group-hover:translate-x-full transition-transform duration-1000"></div>
        <MailOpen class="w-5 h-5 transition-transform group-hover:scale-110 relative z-10" />
        <span class="tracking-[0.2em] uppercase font-sans text-xs md:text-sm font-bold relative z-10">Buka Undangan</span>
      </button>
    </div>
  </div>
</template>

// public/templates/Template 6/src/components/OpeningScreen.tsx
"use client";
import { motion, AnimatePresence } from "framer-motion";
import { MailOpen } from "lucide-react";
import { weddingData } from "@/lib/constants";
import Image from "next/image";

interface OpeningScreenProps {
  isOpen: boolean;
  onOpen: () => void;
  guestName?: string;
}

export default function OpeningScreen({ isOpen, onOpen, guestName }: OpeningScreenProps) {
  return (
    <AnimatePresence>
      {!isOpen && (
        <motion.div
          initial={{ opacity: 1 }}
          exit={{ opacity: 0, y: -100 }}
          transition={{ duration: 1, ease: [0.43, 0.13, 0.23, 0.96] }}
          className="fixed inset-0 z-[100] flex flex-col items-center justify-center overflow-hidden bg-black text-white"
        >
          {/* Background Image with Blur */}
          <div className="absolute inset-0 opacity-60">
            <Image
              src="/assets/Image/hero.webp"
              alt="Background"
              fill
              className="object-cover blur-sm"
              priority
            />
            <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/80" />
          </div>

          {/* Content */}
          <div className="relative z-10 flex flex-col items-center px-6 text-center">
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="mb-4 text-sm font-medium tracking-[0.3em] uppercase opacity-80"
            >
              Wedding Invitation
            </motion.p>

            <motion.h1
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.7, duration: 0.8 }}
              className="mb-2 text-5xl md:text-7xl font-serif text-gold leading-tight"
            >
              {weddingData.couple.groom.firstName} & {weddingData.couple.bride.firstName}
            </motion.h1>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.2 }}
              className="mt-8 mb-12"
            >
              <div className="h-[1px] w-24 bg-gold/50 mx-auto mb-6" />
              <p className="text-xl md:text-2xl font-serif tracking-widest italic">
                {weddingData.event.day}, 15 Maret 2027
              </p>
              <div className="h-[1px] w-24 bg-gold/50 mx-auto mt-6" />
            </motion.div>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.5 }}
              className="mt-4 mb-8 space-y-2"
            >
              <p className="text-xs uppercase tracking-[0.2em] text-white/60 mb-2">Kepada Bapak/Ibu/Saudara/i</p>
              <h2 className="text-2xl md:text-3xl font-serif text-white drop-shadow-md">
                {guestName || "Tamu Terhormat"}
              </h2>
            </motion.div>

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={onOpen}
              className="bg-gold hover:bg-gold/90 text-white px-8 py-4 rounded-full flex items-center gap-3 transition-all duration-300 shadow-lg shadow-gold/20"
            >
              <MailOpen className="h-5 w-5" />
              <span className="font-medium tracking-wide uppercase">Open Invitation</span>
            </motion.button>

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 0.7 }}
              transition={{ delay: 2 }}
              className="mt-12 text-xs italic font-light max-w-xs mx-auto text-white/60 leading-relaxed"
            >
              Mohon maaf apabila ada kesalahan penulisan nama dan gelar.
            </motion.p>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
