// public/templates/Template 15/src/components/Navbar.tsx
"use client";

import { motion } from "framer-motion";
import { Home, Users, Calendar, MessageSquare, Image as ImageIcon, Mail } from "lucide-react/dist/cjs/lucide-react.js";
import { useState, useEffect } from "react";

const navItems = [
  { label: "Home", icon: <Home size={20} />, href: "#" },
  { label: "Mempelai", icon: <Users size={20} />, href: "mempelai" },
  { label: "Acara", icon: <Calendar size={20} />, href: "acara" },
  { label: "Cerita", icon: <MessageSquare size={20} />, href: "cerita" },
  { label: "Galeri", icon: <ImageIcon size={20} />, href: "galeri" },
  { label: "RSVP", icon: <Mail size={20} />, href: "rsvp" },
];

export default function Navbar() {
  const [active, setActive] = useState("#");

  // Track active section on scroll
  useEffect(() => {
    const sectionIds = navItems.map((i) => i.href).filter((h) => h !== "#");

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActive(entry.target.id);
          }
        });
      },
      { rootMargin: "-40% 0px -50% 0px", threshold: 0 }
    );

    sectionIds.forEach((id) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>, href: string) => {
    e.preventDefault();

    if (href === "#") {
      window.scrollTo({ top: 0, behavior: "smooth" });
      setActive("#");
      return;
    }

    const target = document.getElementById(href);
    if (!target) return;

    const top = target.getBoundingClientRect().top + window.scrollY;

    window.scrollTo({ top, behavior: "smooth" });
    setActive(href);
  };

  return (
    <div className="fixed bottom-6 left-0 right-0 z-50 flex justify-center px-4 pointer-events-none">
      <motion.nav
        initial={{ y: 100, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ type: "spring", stiffness: 300, damping: 28, delay: 0.3 }}
        className="pointer-events-auto px-2 py-2 bg-white/90 backdrop-blur-xl rounded-full shadow-2xl border border-white/60 flex items-center gap-0.5"
      >
        {navItems.map((item) => {
          const isActive = active === item.href;
          return (
            <motion.button
              key={item.label}
              onClick={(e) => handleClick(e, item.href)}
              whileTap={{ scale: 0.85 }}
              className={`relative flex items-center justify-center w-11 h-11 rounded-full transition-all duration-300 ${
                isActive ? "text-white" : "text-gray-400 hover:text-soft-purple"
              }`}
            >
              {/* Active pill background */}
              {isActive && (
                <motion.div
                  layoutId="nav-pill"
                  className="absolute inset-0 bg-soft-purple rounded-full"
                  transition={{ type: "spring", stiffness: 400, damping: 30 }}
                />
              )}
              <span className="relative z-10">
                {item.icon}
              </span>
            </motion.button>
          );
        })}
      </motion.nav>
    </div>
  );
}

// public/templates/Template 11/src/components/Navbar.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { Home, Users, Calendar, Image, MessageSquareHeart, Gift } from 'lucide-vue-next'

const navItems = [
  { id: 'hero', icon: Home, label: 'Home' },
  { id: 'couple', icon: Users, label: 'Couple' },
  { id: 'event', icon: Calendar, label: 'Event' },
  { id: 'gallery', icon: Image, label: 'Gallery' },
  { id: 'rsvp', icon: MessageSquareHeart, label: 'RSVP' },
  { id: 'gift', icon: Gift, label: 'Gift' }
]

const activeSection = ref('hero')

const scrollTo = (id) => {
  const el = document.getElementById(id)
  if (el) {
    el.scrollIntoView({ behavior: 'smooth' })
  }
}

const handleScroll = () => {
  const scrollPosition = window.scrollY + window.innerHeight / 2
  for (const item of navItems) {
    const el = document.getElementById(item.id)
    if (el && scrollPosition >= el.offsetTop && scrollPosition < el.offsetTop + el.offsetHeight) {
      activeSection.value = item.id
    }
  }
}

onMounted(() => window.addEventListener('scroll', handleScroll))
onUnmounted(() => window.removeEventListener('scroll', handleScroll))
</script>

<template>
  <Transition name="nav-slide" appear>
    <nav class="fixed bottom-6 left-1/2 -translate-x-1/2 z-[70] w-[90%] max-w-lg">
      <div class="bg-white/60 backdrop-blur-xl border border-white/80 shadow-[0_10px_40px_rgba(0,0,0,0.1)] rounded-[32px] px-4 py-3 flex items-center justify-between">
        <button 
          v-for="item in navItems" 
          :key="item.id"
          @click="scrollTo(item.id)"
          class="flex flex-col items-center gap-1 group transition-all duration-300"
          :class="activeSection === item.id ? 'text-swan-deep' : 'text-swan-deep/30'"
        >
          <div class="p-2 rounded-2xl transition-all duration-300"
               :class="activeSection === item.id ? 'bg-swan-blue/10 scale-110' : 'group-hover:bg-swan-gray group-hover:scale-105'">
            <component :is="item.icon" class="w-5 h-5" />
          </div>
          <span class="text-[8px] tracking-[0.2em] uppercase font-bold transition-opacity duration-300"
                :class="activeSection === item.id ? 'opacity-100' : 'opacity-0'">
            {{ item.label }}
          </span>
        </button>
      </div>
    </nav>
  </Transition>
</template>

<style scoped>
.nav-slide-enter-active {
  transition: all 1.2s cubic-bezier(0.2, 0.8, 0.2, 1);
  transition-delay: 0.8s; /* Muncul saat Opening Scene mulai memudar secara transparan */
}

.nav-slide-enter-from {
  opacity: 0;
  /* Menggunakan translate(-50%, ...) untuk menjaga centering X yang ada di class tailwind */
  transform: translate(-50%, 100px);
}
</style>
