// public/templates/Template 6/src/components/Countdown.tsx
"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { weddingData } from "@/lib/constants";

export default function Countdown() {
  const [timeLeft, setTimeLeft] = useState({
    days: 0,
    hours: 0,
    minutes: 0,
    seconds: 0,
  });

  useEffect(() => {
    const targetDate = new Date(weddingData.event.date).getTime();

    const interval = setInterval(() => {
      const now = new Date().getTime();
      const distance = targetDate - now;

      if (distance < 0) {
        clearInterval(interval);
        return;
      }

      setTimeLeft({
        days: Math.floor(distance / (1000 * 60 * 60 * 24)),
        hours: Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)),
        minutes: Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60)),
        seconds: Math.floor((distance % (1000 * 60)) / 1000),
      });
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const items = [
    { label: "Hari", value: timeLeft.days },
    { label: "Jam", value: timeLeft.hours },
    { label: "Menit", value: timeLeft.minutes },
    { label: "Detik", value: timeLeft.seconds },
  ];

  return (
    <section className="py-20 bg-beige/30">
      <div className="container mx-auto px-6 text-center">
        <motion.h2
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ duration: 1 }}
          viewport={{ once: true }}
          className="text-3xl md:text-4xl font-serif text-gold mb-12"
        >
          Hitung Mundur
        </motion.h2>

        <div className="flex flex-wrap justify-center gap-6 md:gap-12">
          {items.map((item, idx) => (
            <motion.div
              key={item.label}
              initial={{ opacity: 0, scale: 0.5 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{ delay: idx * 0.1, duration: 0.5 }}
              viewport={{ once: true }}
              className="flex flex-col items-center"
            >
              <div className="h-16 w-16 md:h-24 md:w-24 rounded-xl md:rounded-2xl bg-white shadow-soft border border-gold/10 flex items-center justify-center mb-3 md:mb-4">
                <span className="text-2xl md:text-4xl font-serif text-accent">{item.value}</span>
              </div>
              <span className="font-sans text-[10px] md:text-xs uppercase tracking-[0.2em] font-bold text-accent/60">
                {item.label}
              </span>
            </motion.div>
          ))}
        </div>
        
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="mt-16 bg-accent text-white px-8 py-4 rounded-full font-medium tracking-wide shadow-lg"
        >
          Simpan di Kalender
        </motion.button>
      </div>
    </section>
  );
}

// public/templates/Template 10/src/components/Countdown.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const targetDate = new Date('2027-03-15T10:00:00+07:00').getTime()
const days = ref(0)
const hours = ref(0)
const minutes = ref(0)
const seconds = ref(0)

let timer = null

const updateCountdown = () => {
  const now = new Date().getTime()
  const distance = targetDate - now

  if (distance < 0) {
    clearInterval(timer)
    return
  }

  days.value = Math.floor(distance / (1000 * 60 * 60 * 24))
  hours.value = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60))
  minutes.value = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60))
  seconds.value = Math.floor((distance % (1000 * 60)) / 1000)
}

onMounted(() => {
  updateCountdown()
  timer = setInterval(updateCountdown, 1000)
})

onUnmounted(() => {
  clearInterval(timer)
})
</script>

<template>
  <div class="py-20 relative overflow-hidden bg-magical-blue flex flex-col items-center">
    <!-- Section Title -->
    <div class="text-center mb-12 z-10">
      <h2 class="fairytale-font text-5xl md:text-6xl text-magical-gold glow-text-gold mb-4 uppercase tracking-widest">Nantikan Momen Kami</h2>
      <p class="text-magical-gold-light/80 uppercase tracking-[0.3em]">15 Maret 2027</p>
    </div>

    <!-- Countdown Grid -->
    <div class="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-4xl mx-auto px-4 z-10 w-full">
      <div class="glass-panel p-6 flex flex-col items-center group hover:bg-magical-gold/20 transition-colors duration-500">
        <span class="text-5xl font-bold glow-text-gold mb-2">{{ days }}</span>
        <span class="text-sm uppercase tracking-widest text-magical-gold-light">{{ days > 1 ? 'Hari' : 'Hari' }}</span>
      </div>
      <div class="glass-panel p-6 flex flex-col items-center group hover:bg-magical-gold/20 transition-colors duration-500">
        <span class="text-5xl font-bold glow-text-gold mb-2">{{ hours }}</span>
        <span class="text-sm uppercase tracking-widest text-magical-gold-light">Jam</span>
      </div>
      <div class="glass-panel p-6 flex flex-col items-center group hover:bg-magical-gold/20 transition-colors duration-500">
        <span class="text-5xl font-bold glow-text-gold mb-2">{{ minutes }}</span>
        <span class="text-sm uppercase tracking-widest text-magical-gold-light">Menit</span>
      </div>
      <div class="glass-panel p-6 flex flex-col items-center group hover:bg-magical-gold/20 transition-colors duration-500">
        <span class="text-5xl font-bold glow-text-gold mb-2">{{ seconds }}</span>
        <span class="text-sm uppercase tracking-widest text-magical-gold-light">Detik</span>
      </div>
    </div>

    <!-- Save to Calendar Button -->
    <a 
      href="https://calendar.google.com/calendar/render?action=TEMPLATE&text=Wedding+of+Blacky+%26+Cimeng&dates=20270315T100000Z/20270315T150000Z&details=Selamat+datang+di+pernikahan+kami!&location=RT+02,+Desa+Padang+Jaya,+Kec.+Kuaro,+Kab.+Paser,+Kaltim" 
      target="_blank"
      class="mt-12 px-10 py-4 border border-magical-gold text-magical-gold hover:bg-magical-gold hover:text-magical-blue transition-all duration-300 rounded-full uppercase tracking-widest font-bold z-10"
    >
      Simpan Di Kalender
    </a>

    <!-- Decorative Asset -->
    <div 
      class="absolute bottom-0 left-0 w-full h-full opacity-20 pointer-events-none bg-bottom bg-no-repeat bg-contain"
      style="background-image: url('/asset/img/hutan.webp')"
    ></div>
  </div>
</template>
