// public/templates/Template 12/src/components/sections/EventDetails.tsx
"use client";

import React from 'react';
import { motion } from 'framer-motion';
import { MapPin, Clock, Calendar, ExternalLink } from 'lucide-react';
import Image from 'next/image';
import TornEdge from '../ui/TornEdge';
import VintageOrnament from '../ui/VintageOrnament';

const EventDetails = () => {
  const Card = ({ title, date, time, location, gmapsLink }: any) => (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="bg-white/50 backdrop-blur-md border border-vintage-gold/20 p-8 md:p-12 rounded-3xl relative overflow-hidden group hover:border-vintage-gold/50 transition-all duration-500 shadow-2xl"
    >
      <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:opacity-20 transition-opacity grayscale sepia">
        <VintageOrnament className="w-32 h-32" />
      </div>
      
      <h3 className="script-text text-6xl text-vintage-brown mb-8 gold-glow">{title}</h3>
      
      <div className="space-y-8 text-left relative z-10">
        <div className="flex items-start gap-5">
          <div className="bg-vintage-gold/10 p-4 rounded-full text-vintage-gold border border-vintage-gold/20 shadow-inner">
            <Calendar size={22} />
          </div>
          <div>
            <p className="serif-text font-bold text-vintage-brown uppercase tracking-widest text-xs mb-1">Hari / Tanggal</p>
            <p className="serif-text text-vintage-brown text-lg weathered-text">{date}</p>
          </div>
        </div>

        <div className="flex items-start gap-5">
          <div className="bg-vintage-gold/10 p-4 rounded-full text-vintage-gold border border-vintage-gold/20 shadow-inner">
            <Clock size={22} />
          </div>
          <div>
            <p className="serif-text font-bold text-vintage-brown uppercase tracking-widest text-xs mb-1">Waktu</p>
            <p className="serif-text text-vintage-brown text-lg weathered-text">{time}</p>
          </div>
        </div>

        <div className="flex items-start gap-5">
          <div className="bg-vintage-gold/10 p-4 rounded-full text-vintage-gold border border-vintage-gold/20 shadow-inner">
            <MapPin size={22} />
          </div>
          <div>
            <p className="serif-text font-bold text-vintage-brown uppercase tracking-widest text-xs mb-1">Lokasi</p>
            <p className="serif-text text-base leading-relaxed text-vintage-brown weathered-text">{location}</p>
          </div>
        </div>
      </div>

      <div className="mt-12 pt-10 border-t border-vintage-gold/20 flex items-center gap-4">
        <div className="w-2 h-2 bg-vintage-gold rounded-full opacity-50"></div>
        <div className="flex-1">
          <p className="serif-text text-[10px] uppercase tracking-[0.3em] text-vintage-brown/60 mb-1">Dress Code:</p>
          <p className="serif-text text-sm italic text-vintage-brown-dark weathered-text">Busana batik dan bersepatu.</p>
        </div>
      </div>

      <motion.a
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        href={gmapsLink}
        target="_blank"
        rel="noopener noreferrer"
        className="mt-10 flex items-center justify-center gap-3 bg-vintage-brown text-vintage-cream py-5 rounded-2xl shadow-xl hover:bg-vintage-gold transition-all group overflow-hidden relative"
      >
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/old-paper.png')] opacity-10"></div>
        <ExternalLink size={20} className="group-hover:rotate-12 transition-transform" />
        <span className="serif-text font-bold text-sm tracking-[0.2em] uppercase">Buka Google Maps</span>
      </motion.a>
    </motion.div>
  );

  return (
    <section id="acara" className="py-24 relative overflow-hidden bg-vintage-ivory/50">
      <TornEdge position="top" />
      
      <div className="container mx-auto px-6 relative z-10 pt-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-20"
        >
          <h2 className="script-text text-7xl text-vintage-brown gold-glow">Momen Bahagia</h2>
          <div className="h-[1.5px] w-32 bg-gradient-to-r from-transparent via-vintage-gold/50 to-transparent mx-auto mt-6"></div>
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-12 max-w-6xl mx-auto">
          <Card
            title="Akad Nikah"
            date="Rabu, 15 Maret 2027"
            time="10.00 WIB — Selesai"
            location="RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur 76281"
            gmapsLink="https://maps.google.com/?q=RT+02,+Desa+Padang+Jaya,+Kec.+Kuaro,+Kab.+Paser"
          />
          <Card
            title="Resepsi"
            date="Rabu, 15 Maret 2027"
            time="13.00 WIB — Selesai"
            location="RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur 76281"
            gmapsLink="https://maps.google.com/?q=RT+02,+Desa+Padang+Jaya,+Kec.+Kuaro,+Kab.+Paser"
          />
        </div>

        {/* Dummy Map Embed Placeholder */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-20 rounded-3xl overflow-hidden shadow-2xl border-4 border-white/50 grayscale-[50%] hover:grayscale-0 transition-all duration-700 h-[400px] relative"
        >
          <iframe 
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15951.68351543169!2d116.0371!3d-1.8974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMcKwNTMnNTAuNiJTIDExNsKwMDInMTMuNiJF!5e0!3m2!1sid!2sid!4v1620000000000!5m2!1sid!2sid" 
            width="100%" 
            height="100%" 
            style={{ border: 0 }} 
            allowFullScreen 
            loading="lazy"
          ></iframe>
        </motion.div>
      </div>

      {/* Corner Ornaments */}
      <VintageOrnament className="absolute top-10 left-10 w-48 h-48 opacity-10 pointer-events-none rotate-180" />
      <VintageOrnament className="absolute bottom-10 right-10 w-48 h-48 opacity-10 pointer-events-none" />
    </section>
  );
};

export default EventDetails;

// public/templates/Template 10/src/components/EventDetails.vue
<script setup>
import { onMounted, ref } from 'vue'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'

gsap.registerPlugin(ScrollTrigger)
const sectionRef = ref(null)

onMounted(() => {
  gsap.from(sectionRef.value, {
    scrollTrigger: {
      trigger: sectionRef.value,
      start: "top bottom",
      end: "top center",
      scrub: 1,
    },
    rotationX: -15,
    transformOrigin: "top center",
    opacity: 0,
    ease: "none"
  })
})
</script>

<template>
  <div ref="sectionRef" class="py-32 bg-magical-blue relative overflow-hidden" style="perspective: 2000px;">
    <!-- Parallax Background -->
    <div 
      class="absolute inset-0 bg-cover bg-fixed bg-center opacity-10"
      style="background-image: url('/asset/img/hutan.webp')"
    ></div>
    <!-- Dark overlay -->
    <div class="absolute inset-0 bg-magical-blue/60 backdrop-blur-sm"></div>

    <!-- Floating Lanterns & Particles -->
    <div class="absolute top-0 right-0 w-64 h-64 opacity-20 pointer-events-none">
      <div class="w-full h-full lantern-light"></div>
    </div>
    <!-- Floating Particles -->
    <div class="absolute inset-0 pointer-events-none overflow-hidden">
      <div v-for="i in 25" :key="i" 
        class="absolute w-1 h-1 md:w-1.5 md:h-1.5 bg-magical-gold/30 rounded-full blur-[1px] animate-float-optimized will-change-transform" 
        :style="{ 
          left: Math.random() * 100 + '%', 
          top: Math.random() * 100 + '%', 
          animationDelay: Math.random() * 5 + 's', 
          animationDuration: 4 + Math.random() * 4 + 's' 
        }"
      ></div>
    </div>

    <div class="max-w-6xl mx-auto px-4 relative z-10 text-center">
      <!-- Section Header -->
      <div class="mb-24 relative z-10">
        <h2 class="fairytale-font text-6xl md:text-8xl text-transparent bg-clip-text bg-gradient-to-r from-magical-gold-light via-magical-gold to-magical-gold-light glow-text-gold mb-6 drop-shadow-2xl">Informasi Acara</h2>
        <div class="flex items-center justify-center gap-4">
          <div class="h-px w-16 md:w-32 bg-gradient-to-r from-transparent to-magical-gold"></div>
          <span class="text-magical-gold/80 tracking-[0.3em] uppercase text-sm md:text-base font-bold">Simpan di Kalender</span>
          <div class="h-px w-16 md:w-32 bg-gradient-to-l from-transparent to-magical-gold"></div>
        </div>
      </div>

      <div class="grid md:grid-cols-2 gap-16 md:gap-20">
        <!-- Akad Nikah -->
        <div class="relative group">
          <div class="absolute inset-0 bg-magical-gold/10 blur-[80px] rounded-[3rem] opacity-0 group-hover:opacity-100 transition-opacity duration-1000"></div>
          <div class="relative bg-white/5 backdrop-blur-md rounded-[3rem] p-10 md:p-14 border border-white/10 shadow-[0_0_40px_rgba(30,10,40,0.5)] hover:-translate-y-4 transition-transform duration-500 overflow-hidden">
            <!-- Corner Ornaments -->
            <div class="absolute top-6 left-6 w-12 h-12 border-t-2 border-l-2 border-magical-gold/50 rounded-tl-2xl"></div>
            <div class="absolute bottom-6 right-6 w-12 h-12 border-b-2 border-r-2 border-magical-gold/50 rounded-br-2xl"></div>
            
            <h3 class="fairytale-font text-5xl text-white mb-8 glow-text-purple tracking-wide">Akad Nikah</h3>
            <div class="h-px w-24 bg-gradient-to-r from-transparent via-magical-gold to-transparent mx-auto mb-8"></div>
            
            <div class="space-y-8 text-white/90">
              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Hari & Tanggal</span>
                <p class="text-xl font-light">Rabu, 15 Maret 2027</p>
              </div>
              
              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Waktu</span>
                <p class="text-xl font-light">10.00 WIB — Selesai</p>
              </div>
              
              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Lokasi</span>
                <p class="leading-relaxed font-light text-center max-w-[250px]">
                  RT 02, Desa Padang Jaya, Kec. Kuaro, <br> Kab. Paser, Kaltim 76281
                </p>
              </div>

              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Dress Code</span>
                <p class="font-light italic">Busana batik dan bersepatu.</p>
              </div>
            </div>

            <a href="https://maps.apple.com/?address=Padang%20Jaya,%20Kalimantan%20Timur,%20Indonesia" target="_blank" class="mt-12 inline-flex items-center gap-3 px-8 py-3 rounded-full border border-magical-gold/40 text-magical-gold hover:bg-magical-gold hover:text-magical-blue transition-all duration-500 shadow-[0_0_15px_rgba(212,175,55,0.2)] hover:shadow-[0_0_25px_rgba(212,175,55,0.6)] group-hover:scale-105">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
              <span class="font-bold tracking-[0.2em] text-sm">GOOGLE MAPS</span>
            </a>
          </div>
        </div>

        <!-- Resepsi -->
        <div class="relative group">
          <div class="absolute inset-0 bg-magical-gold/10 blur-[80px] rounded-[3rem] opacity-0 group-hover:opacity-100 transition-opacity duration-1000"></div>
          <div class="relative bg-white/5 backdrop-blur-md rounded-[3rem] p-10 md:p-14 border border-white/10 shadow-[0_0_40px_rgba(30,10,40,0.5)] hover:-translate-y-4 transition-transform duration-500 overflow-hidden">
            <!-- Corner Ornaments -->
            <div class="absolute top-6 right-6 w-12 h-12 border-t-2 border-r-2 border-magical-gold/50 rounded-tr-2xl"></div>
            <div class="absolute bottom-6 left-6 w-12 h-12 border-b-2 border-l-2 border-magical-gold/50 rounded-bl-2xl"></div>
            
            <h3 class="fairytale-font text-5xl text-white mb-8 glow-text-purple tracking-wide">Resepsi</h3>
            <div class="h-px w-24 bg-gradient-to-r from-transparent via-magical-gold to-transparent mx-auto mb-8"></div>
            
            <div class="space-y-8 text-white/90">
              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Hari & Tanggal</span>
                <p class="text-xl font-light">Rabu, 15 Maret 2027</p>
              </div>
              
              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Waktu</span>
                <p class="text-xl font-light">13.00 WIB — Selesai</p>
              </div>
              
              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Lokasi</span>
                <p class="leading-relaxed font-light text-center max-w-[250px]">
                  RT 02, Desa Padang Jaya, Kec. Kuaro, <br> Kab. Paser, Kaltim 76281
                </p>
              </div>

              <div class="flex flex-col items-center gap-2">
                <span class="text-magical-gold font-bold uppercase tracking-[0.2em] text-xs">Dress Code</span>
                <p class="font-light italic">Busana batik dan bersepatu.</p>
              </div>
            </div>

            <a href="https://maps.apple.com/?address=Padang%20Jaya,%20Kalimantan%20Timur,%20Indonesia" target="_blank" class="mt-12 inline-flex items-center gap-3 px-8 py-3 rounded-full border border-magical-gold/40 text-magical-gold hover:bg-magical-gold hover:text-magical-blue transition-all duration-500 shadow-[0_0_15px_rgba(212,175,55,0.2)] hover:shadow-[0_0_25px_rgba(212,175,55,0.6)] group-hover:scale-105">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
              <span class="font-bold tracking-[0.2em] text-sm">GOOGLE MAPS</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
