// public/templates/Template 6/src/components/Gift.tsx
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Copy, CreditCard, Gift as GiftIcon, MapPin } from "lucide-react";
import { weddingData } from "@/lib/constants";
import { useState } from "react";
import Image from "next/image";

export default function Gift() {
  const [copiedAccount, setCopiedAccount] = useState(false);
  const [copiedAddress, setCopiedAddress] = useState(false);
  const [showGifts, setShowGifts] = useState(false);

  const copyToClipboard = (text: string, type: "account" | "address") => {
    navigator.clipboard.writeText(text);
    if (type === "account") {
      setCopiedAccount(true);
      setTimeout(() => setCopiedAccount(false), 2000);
    } else {
      setCopiedAddress(true);
      setTimeout(() => setCopiedAddress(false), 2000);
    }
  };

  return (
    <section className="py-24 bg-beige/10">
      <div className="container mx-auto px-6 max-w-5xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <span className="font-sans text-xs tracking-[0.4em] uppercase font-bold text-gold/60 mb-4 block">Gifts</span>
          <h2 className="text-4xl md:text-5xl font-serif text-accent mb-6">Love Gift</h2>
          <p className="text-sm text-accent/70 max-w-lg mx-auto leading-relaxed">
            Doa restu Anda merupakan hadiah terindah bagi kami. Namun bagi Anda yang ingin memberikan tanda kasih, dapat melalui:
          </p>
          <button
            onClick={() => setShowGifts(!showGifts)}
            className="mt-10 bg-gold text-white px-10 py-4 rounded-full text-xs font-bold uppercase tracking-widest hover:bg-gold/90 transition-all shadow-lg shadow-gold/20 flex items-center gap-3 mx-auto"
          >
            <GiftIcon className="h-4 w-4" />
            {showGifts ? "Tutup Pilihan Kado" : "Kirim Hadiah"}
          </button>
        </motion.div>

        <AnimatePresence>
          {showGifts && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.5, ease: "easeInOut" }}
              className="overflow-hidden"
            >
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 pt-10">
                {/* Bank Card */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-white p-8 rounded-[2rem] shadow-soft border border-gold/5 flex flex-col items-center text-center"
                >
                  <div className="h-14 w-14 rounded-full bg-gold/5 flex items-center justify-center mb-6">
                      <CreditCard className="h-7 w-7 text-gold" />
                  </div>
                  <h3 className="text-xl font-serif text-accent mb-2">{weddingData.gift.bank.name}</h3>
                  <p className="text-2xl font-sans tracking-widest font-bold text-accent mb-2">
                      {weddingData.gift.bank.accountNumber}
                  </p>
                  <p className="text-xs uppercase tracking-widest text-accent/50 mb-8">
                      Atas Nama: {weddingData.gift.bank.accountHolder}
                  </p>
                  <button
                      onClick={() => copyToClipboard(weddingData.gift.bank.accountNumber, "account")}
                      className="inline-flex items-center gap-2 bg-gold/10 hover:bg-gold/20 text-gold px-6 py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all"
                  >
                      <Copy className="h-4 w-4" />
                      {copiedAccount ? "Tersalin!" : "Salin Rekening"}
                  </button>
                </motion.div>

                {/* QRIS Card */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                  className="bg-white p-8 rounded-[2rem] shadow-soft border border-gold/5 flex flex-col items-center text-center"
                >
                  <div className="h-14 w-14 rounded-full bg-gold/5 flex items-center justify-center mb-6">
                      <GiftIcon className="h-7 w-7 text-gold" />
                  </div>
                  <h3 className="text-xl font-serif text-accent mb-6">QRIS {weddingData.gift.qris.name}</h3>
                  <div className="relative w-40 h-40 mb-6 bg-beige/5 rounded-xl border border-gold/10 p-2">
                      <Image 
                          src={weddingData.gift.qris.image} 
                          alt="QRIS" 
                          fill 
                          className="object-contain p-2"
                      />
                  </div>
                  <p className="text-xs uppercase tracking-widest text-accent/50 mb-4">
                      Pindai untuk kirim tanda kasih
                  </p>
                  <button
                      className="inline-flex items-center gap-2 bg-accent text-white px-6 py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all"
                  >
                      Kirim Kado
                  </button>
                </motion.div>

                {/* Shipping Card */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.2 }}
                  className="bg-white p-8 rounded-[2rem] shadow-soft border border-gold/5 flex flex-col items-center text-center md:col-span-2 lg:col-span-1"
                >
                  <div className="h-14 w-14 rounded-full bg-gold/5 flex items-center justify-center mb-6">
                      <MapPin className="h-7 w-7 text-gold" />
                  </div>
                  <h3 className="text-xl font-serif text-accent mb-6">Alamat Pengiriman</h3>
                  <p className="text-sm text-accent/70 mb-8 leading-relaxed italic px-4">
                      {weddingData.gift.delivery.address}
                  </p>
                  <button
                      onClick={() => copyToClipboard(weddingData.gift.delivery.address, "address")}
                      className="inline-flex items-center gap-2 bg-gold/10 hover:bg-gold/20 text-gold px-6 py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all"
                  >
                      <Copy className="h-4 w-4" />
                      {copiedAddress ? "Tersalin!" : "Salin Alamat"}
                  </button>
                </motion.div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}

// public/templates/Template 10/src/components/Gift.vue
<script setup>
import { ref, onMounted } from 'vue'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'

gsap.registerPlugin(ScrollTrigger)
const sectionRef = ref(null)

const isRevealed = ref(false)

const copyToClipboard = (text) => {
  navigator.clipboard.writeText(text)
  alert('Berhasil disalin: ' + text)
}

onMounted(() => {
  gsap.from(sectionRef.value, {
    scrollTrigger: {
      trigger: sectionRef.value,
      start: "top bottom",
      end: "top center",
      scrub: 1,
    },
    rotationX: -20,
    transformOrigin: "top center",
    opacity: 0,
    ease: "none"
  })
})
</script>

<template>
  <div ref="sectionRef" class="py-32 bg-magical-blue relative overflow-hidden" style="perspective: 2000px;">
    <!-- Starry overlay -->
    <div class="absolute inset-0 opacity-10 pointer-events-none bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-white via-transparent to-transparent"></div>

    <div class="max-w-5xl mx-auto px-4 relative z-10 text-center">
      <!-- Section Header -->
      <div class="mb-24 relative z-10">
        <h2 class="fairytale-font text-6xl md:text-8xl text-transparent bg-clip-text bg-gradient-to-r from-magical-gold-light via-magical-gold to-magical-gold-light glow-text-gold mb-6 drop-shadow-2xl">Gift & Kadou</h2>
        <div class="flex items-center justify-center gap-4">
          <div class="h-px w-16 md:w-32 bg-gradient-to-r from-transparent to-magical-gold"></div>
          <span class="text-magical-gold/80 tracking-[0.3em] uppercase text-sm md:text-base font-bold">Tanda Kasih</span>
          <div class="h-px w-16 md:w-32 bg-gradient-to-l from-transparent to-magical-gold"></div>
        </div>
      </div>

      <!-- Trigger Button container -->
      <div v-if="!isRevealed" class="flex justify-center items-center py-10 relative z-20">
        <button 
          @click="isRevealed = true"
          class="px-10 py-5 bg-gradient-to-r from-magical-gold to-magical-gold-light text-magical-purple font-bold rounded-full shadow-[0_0_30px_rgba(212,175,55,0.6)] hover:scale-105 transition-all duration-500 uppercase tracking-widest border-2 border-white/20 text-lg flex items-center gap-3 animate-pulse group"
        >
          <svg class="w-6 h-6 group-hover:rotate-12 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/></svg>
          Buka Tanda Kasih
        </button>
      </div>

      <!-- Wrapped Content -->
      <div v-else class="animate-fade-in-up">
        <div class="grid md:grid-cols-2 gap-12 md:gap-16">
          <!-- Bank Card -->
          <div class="relative group">
            <div class="absolute inset-0 bg-magical-gold/5 blur-[50px] rounded-[3rem] opacity-0 group-hover:opacity-100 transition-opacity duration-700"></div>
            <div class="relative bg-white/5 backdrop-blur-md rounded-[3rem] p-10 md:p-12 border border-white/10 shadow-[0_0_30px_rgba(0,0,0,0.4)] flex flex-col items-center transition-all duration-500 hover:-translate-y-2 hover:border-magical-gold/30">
              <div class="w-20 h-20 bg-white/5 rounded-full border border-magical-gold/20 flex items-center justify-center mb-8 shadow-[0_0_20px_rgba(212,175,55,0.2)] group-hover:scale-110 transition-transform duration-500">
                <svg class="w-10 h-10 text-magical-gold" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"/></svg>
              </div>
              <h3 class="fairytale-font text-4xl text-white mb-4">BANK BRI</h3>
              <div class="h-px w-12 bg-magical-gold/50 mb-6"></div>
              <p class="text-magical-gold-light text-3xl font-bold mb-4 tracking-widest">0822 2924 3737</p>
              <p class="text-white/70 mb-8 uppercase tracking-[0.2em] text-sm">Atas Nama: Andro</p>
              <button 
                @click="copyToClipboard('082229243737')"
                class="px-8 py-3 bg-magical-gold/10 border border-magical-gold/50 text-magical-gold hover:bg-magical-gold hover:text-magical-purple transition-colors duration-300 rounded-full text-sm font-bold uppercase tracking-widest w-full max-w-xs"
              >
                Salin Rekening
              </button>
            </div>
          </div>

          <!-- QRIS Card -->
          <div class="relative group">
            <div class="absolute inset-0 bg-magical-gold/5 blur-[50px] rounded-[3rem] opacity-0 group-hover:opacity-100 transition-opacity duration-700"></div>
            <div class="relative bg-white/5 backdrop-blur-md rounded-[3rem] p-10 md:p-12 border border-white/10 shadow-[0_0_30px_rgba(0,0,0,0.4)] flex flex-col items-center transition-all duration-500 hover:-translate-y-2 hover:border-magical-gold/30">
              <div class="w-20 h-20 bg-white/5 rounded-full border border-magical-gold/20 flex items-center justify-center mb-8 shadow-[0_0_20px_rgba(212,175,55,0.2)] group-hover:scale-110 transition-transform duration-500">
                <svg class="w-10 h-10 text-magical-gold" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z"/></svg>
              </div>
              <h3 class="fairytale-font text-4xl text-white mb-6">QRIS YUKI</h3>
              <div class="w-48 h-48 bg-white p-2 rounded-2xl mb-8 flex items-center justify-center shadow-lg transform group-hover:scale-110 transition-transform duration-500 overflow-hidden">
                <img src="/asset/img/donate.webp" alt="QRIS YUKI" class="w-full h-full object-contain" loading="lazy" />
              </div>
              <p class="text-white/60 uppercase tracking-[0.2em] text-xs">Pindai untuk mengirim</p>
            </div>
          </div>
        </div>

        <!-- Address Card -->
        <div class="mt-16 max-w-2xl mx-auto relative group">
          <div class="absolute inset-0 bg-magical-gold/5 blur-[50px] rounded-[3rem] opacity-0 group-hover:opacity-100 transition-opacity duration-700"></div>
          <div class="relative bg-white/5 backdrop-blur-md rounded-[3rem] p-10 md:p-12 border border-white/10 shadow-[0_0_30px_rgba(0,0,0,0.4)] transition-all duration-500 hover:-translate-y-2 hover:border-magical-gold/30">
            <h3 class="fairytale-font text-4xl text-white mb-6">Kirim Kado</h3>
            <div class="h-px w-24 bg-gradient-to-r from-transparent via-magical-gold to-transparent mx-auto mb-6"></div>
            <p class="text-white/80 max-w-lg mx-auto mb-8 font-light leading-relaxed">
              RT 02, Desa Padang Jaya, Kec. Kuaro, <br> Kab. Paser, Kalimantan Timur 76281
            </p>
            <button 
              @click="copyToClipboard('RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur 76281')"
              class="px-10 py-4 bg-magical-gold text-magical-purple font-bold rounded-full hover:bg-white transition-colors uppercase tracking-[0.2em] text-sm shadow-[0_0_20px_rgba(212,175,55,0.3)] hover:shadow-[0_0_30px_rgba(255,255,255,0.5)]"
            >
              Salin Alamat
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
