// public/templates/Template 12/src/components/Navbar.tsx
"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Home, User, Heart, Calendar, Image as ImageIcon, Gift, MessageSquare } from 'lucide-react';

const Navbar = () => {
  const [isVisible, setIsVisible] = useState(false);
  const [activeSection, setActiveSection] = useState('hero');

  useEffect(() => {
    const handleScroll = () => {
      const scrolled = window.scrollY > 300;
      setIsVisible(scrolled);

      const sections = ['hero', 'mempelai', 'story', 'countdown', 'acara', 'gallery', 'gift', 'rsvp'];
      for (const section of sections) {
        const element = document.getElementById(section);
        if (element) {
          const rect = element.getBoundingClientRect();
          if (rect.top >= 0 && rect.top <= 300) {
            setActiveSection(section);
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const navItems = [
    { id: 'hero', icon: <Home size={18} />, label: 'Home' },
    { id: 'mempelai', icon: <User size={18} />, label: 'Pasangan' },
    { id: 'story', icon: <Heart size={18} />, label: 'Kisah' },
    { id: 'acara', icon: <Calendar size={18} />, label: 'Acara' },
    { id: 'gallery', icon: <ImageIcon size={18} />, label: 'Galeri' },
    { id: 'gift', icon: <Gift size={18} />, label: 'Hadiah' },
    { id: 'rsvp', icon: <MessageSquare size={18} />, label: 'Pesan' },
  ];

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.nav
          initial={{ y: 100, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: 100, opacity: 0 }}
          className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[4000] px-4"
        >
          <div className="bg-vintage-cream/80 backdrop-blur-md border border-vintage-gold/30 px-4 py-2 rounded-full shadow-2xl flex items-center gap-1 relative overflow-hidden">
             {/* Texture inside navbar */}
             <div className="absolute inset-0 opacity-20 pointer-events-none bg-[url('https://www.transparenttextures.com/patterns/old-paper.png')]"></div>
             
             {navItems.map((item) => (
               <a
                 key={item.id}
                 href={`#${item.id}`}
                 onClick={() => setActiveSection(item.id)}
                 className={`relative z-10 p-3 rounded-full transition-all duration-300 flex flex-col items-center group ${
                   activeSection === item.id ? 'text-vintage-gold scale-110' : 'text-vintage-brown/50 hover:text-vintage-brown'
                 }`}
               >
                 {item.icon}
                 <span className="absolute -top-10 bg-vintage-brown text-vintage-cream text-[10px] px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none serif-text">
                   {item.label}
                 </span>
                 {activeSection === item.id && (
                   <motion.div
                     layoutId="activeNav"
                     className="absolute inset-0 bg-vintage-gold/10 rounded-full -z-10"
                   />
                 )}
               </a>
             ))}
          </div>
        </motion.nav>
      )}
    </AnimatePresence>
  );
};

export default Navbar;

// public/templates/Template 7/src/components/Navbar.vue
<script setup lang="ts">
import { Home, Users, Heart, Image as ImageIcon, CheckCircle, Gift } from 'lucide-vue-next'
import { ref, onMounted } from 'vue'

const activeSection = ref('hero')

const updateActiveSection = () => {
  const sections = ['hero', 'couple', 'event', 'story', 'gallery', 'gift', 'rsvp']
  for (const id of sections) {
    const el = document.getElementById(id)
    if (el) {
      const rect = el.getBoundingClientRect()
      if (rect.top <= 100 && rect.bottom >= 100) {
        activeSection.value = id
        break
      }
    }
  }
}

onMounted(() => {
  window.addEventListener('scroll', updateActiveSection)
  updateActiveSection()
})
</script>

<template>
  <nav class="fixed bottom-6 md:bottom-8 left-1/2 -translate-x-1/2 z-[100] w-[90%] max-w-lg">
    <div class="glass border border-white/50 px-4 md:px-8 py-3 rounded-full shadow-[0_20px_50px_rgba(183,110,121,0.2)] flex gap-2 md:gap-4 items-center justify-between">
      
      <a v-for="item in [
        { id: 'hero', icon: Home, label: 'Beranda' },
        { id: 'couple', icon: Users, label: 'Mempelai' },
        { id: 'event', icon: CheckCircle, label: 'Acara' },
        { id: 'gallery', icon: ImageIcon, label: 'Galeri' },
        { id: 'gift', icon: Gift, label: 'Kado' },
        { id: 'rsvp', icon: Heart, label: 'RSVP' }
      ]" 
      :key="item.id"
      :href="'#' + item.id" 
      class="relative flex flex-col items-center gap-1 group py-1 px-3 transition-all duration-300"
      :class="[activeSection === item.id ? 'text-rose-gold scale-110' : 'text-gray-400']"
      >
        <component :is="item.icon" class="w-5 h-5 md:w-6 md:h-6 transition-transform group-hover:scale-110" />
        <span class="text-[8px] md:text-[10px] uppercase tracking-widest font-bold opacity-0 group-hover:opacity-100 transition-opacity absolute -top-8 bg-rose-gold text-white px-2 py-1 rounded shadow-lg pointer-events-none whitespace-nowrap">
          {{ item.label }}
        </span>
        
        <!-- Active Dot -->
        <div v-show="activeSection === item.id" class="absolute -bottom-1 w-1 h-1 bg-rose-gold rounded-full shadow-[0_0_8px_rgba(183,110,121,0.8)]"></div>
      </a>

    </div>
  </nav>
</template>

<style scoped>
.glass {
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(15px);
  -webkit-backdrop-filter: blur(15px);
}
</style>
