// public/templates/Template 15/src/components/Navbar.tsx
"use client";

import { motion } from "framer-motion";
import { Home, Users, Calendar, MessageSquare, Image as ImageIcon, Mail } from "lucide-react/dist/cjs/lucide-react.js";
import { useState, useEffect } from "react";

const navItems = [
  { label: "Home", icon: <Home size={20} />, href: "#" },
  { label: "Mempelai", icon: <Users size={20} />, href: "mempelai" },
  { label: "Acara", icon: <Calendar size={20} />, href: "acara" },
  { label: "Cerita", icon: <MessageSquare size={20} />, href: "cerita" },
  { label: "Galeri", icon: <ImageIcon size={20} />, href: "galeri" },
  { label: "RSVP", icon: <Mail size={20} />, href: "rsvp" },
];

export default function Navbar() {
  const [active, setActive] = useState("#");

  // Track active section on scroll
  useEffect(() => {
    const sectionIds = navItems.map((i) => i.href).filter((h) => h !== "#");

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActive(entry.target.id);
          }
        });
      },
      { rootMargin: "-40% 0px -50% 0px", threshold: 0 }
    );

    sectionIds.forEach((id) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>, href: string) => {
    e.preventDefault();

    if (href === "#") {
      window.scrollTo({ top: 0, behavior: "smooth" });
      setActive("#");
      return;
    }

    const target = document.getElementById(href);
    if (!target) return;

    const top = target.getBoundingClientRect().top + window.scrollY;

    window.scrollTo({ top, behavior: "smooth" });
    setActive(href);
  };

  return (
    <div className="fixed bottom-6 left-0 right-0 z-50 flex justify-center px-4 pointer-events-none">
      <motion.nav
        initial={{ y: 100, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ type: "spring", stiffness: 300, damping: 28, delay: 0.3 }}
        className="pointer-events-auto px-2 py-2 bg-white/90 backdrop-blur-xl rounded-full shadow-2xl border border-white/60 flex items-center gap-0.5"
      >
        {navItems.map((item) => {
          const isActive = active === item.href;
          return (
            <motion.button
              key={item.label}
              onClick={(e) => handleClick(e, item.href)}
              whileTap={{ scale: 0.85 }}
              className={`relative flex items-center justify-center w-11 h-11 rounded-full transition-all duration-300 ${
                isActive ? "text-white" : "text-gray-400 hover:text-soft-purple"
              }`}
            >
              {/* Active pill background */}
              {isActive && (
                <motion.div
                  layoutId="nav-pill"
                  className="absolute inset-0 bg-soft-purple rounded-full"
                  transition={{ type: "spring", stiffness: 400, damping: 30 }}
                />
              )}
              <span className="relative z-10">
                {item.icon}
              </span>
            </motion.button>
          );
        })}
      </motion.nav>
    </div>
  );
}

// public/templates/Template 7/src/components/Navbar.vue
<script setup lang="ts">
import { Home, Users, Heart, Image as ImageIcon, CheckCircle, Gift } from 'lucide-vue-next'
import { ref, onMounted } from 'vue'

const activeSection = ref('hero')

const updateActiveSection = () => {
  const sections = ['hero', 'couple', 'event', 'story', 'gallery', 'gift', 'rsvp']
  for (const id of sections) {
    const el = document.getElementById(id)
    if (el) {
      const rect = el.getBoundingClientRect()
      if (rect.top <= 100 && rect.bottom >= 100) {
        activeSection.value = id
        break
      }
    }
  }
}

onMounted(() => {
  window.addEventListener('scroll', updateActiveSection)
  updateActiveSection()
})
</script>

<template>
  <nav class="fixed bottom-6 md:bottom-8 left-1/2 -translate-x-1/2 z-[100] w-[90%] max-w-lg">
    <div class="glass border border-white/50 px-4 md:px-8 py-3 rounded-full shadow-[0_20px_50px_rgba(183,110,121,0.2)] flex gap-2 md:gap-4 items-center justify-between">
      
      <a v-for="item in [
        { id: 'hero', icon: Home, label: 'Beranda' },
        { id: 'couple', icon: Users, label: 'Mempelai' },
        { id: 'event', icon: CheckCircle, label: 'Acara' },
        { id: 'gallery', icon: ImageIcon, label: 'Galeri' },
        { id: 'gift', icon: Gift, label: 'Kado' },
        { id: 'rsvp', icon: Heart, label: 'RSVP' }
      ]" 
      :key="item.id"
      :href="'#' + item.id" 
      class="relative flex flex-col items-center gap-1 group py-1 px-3 transition-all duration-300"
      :class="[activeSection === item.id ? 'text-rose-gold scale-110' : 'text-gray-400']"
      >
        <component :is="item.icon" class="w-5 h-5 md:w-6 md:h-6 transition-transform group-hover:scale-110" />
        <span class="text-[8px] md:text-[10px] uppercase tracking-widest font-bold opacity-0 group-hover:opacity-100 transition-opacity absolute -top-8 bg-rose-gold text-white px-2 py-1 rounded shadow-lg pointer-events-none whitespace-nowrap">
          {{ item.label }}
        </span>
        
        <!-- Active Dot -->
        <div v-show="activeSection === item.id" class="absolute -bottom-1 w-1 h-1 bg-rose-gold rounded-full shadow-[0_0_8px_rgba(183,110,121,0.8)]"></div>
      </a>

    </div>
  </nav>
</template>

<style scoped>
.glass {
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(15px);
  -webkit-backdrop-filter: blur(15px);
}
</style>
