// public/templates/Template 11/src/components/LoveStory.vue
<script setup>
import Swan from './Swan.vue'

const stories = [
  {
    number: '01',
    year: 'Januari',
    date: '2026',
    title: 'Awal Pertemuan Sederhana',
      desc: 'Di balik dinginnya gudang tua, dua pasang mata bertemu. Franz, sang penguasa bayangan, menemukan Rosie yang seputih salju. Sebuah kontras yang melahirkan harmoni.',
    extra: 'Takdir mempertemukan mereka dalam keheningan yang bicara lebih banyak dari kata-kata.',
    img: '/Asset/Image/galery.webp',
    accent: 'bg-swan-blue/20'
  },
  {
    number: '02',
    year: 'Februari',
    date: '2026',
    title: 'Benih Cinta dalam Ujian',
      desc: 'Krisis melanda wilayah mereka, namun di sanalah strategi "Gerakan Senyap" Rosie membuktikan bahwa kecantikan hanyalah selapis dari kecerdasannya yang luar biasa.',
      extra: 'Franz terpesona, bukan hanya oleh rupa, tapi oleh jiwa yang tangguh di balik bulu putih itu.',
    img: '/Asset/Image/galery2.webp',
    accent: 'bg-swan-silver/10'
  },
  {
    number: '03',
    year: 'Maret',
    date: '2026',
    title: 'Langkah Menuju Ridha Allah',
      desc: 'Proses taaruf yang tulus membawa Franz ke hadapan keluarga Rosie. Keikhlasan visi hidupnya meruntuhkan segala keraguan, menyatukan dua keluarga dalam restu.',
    extra: 'Di taman belakang yang saksi bisu, sebuah janji suci mulai dirajut menuju masa depan.',
    img: '/Asset/Image/galery3.webp',
    accent: 'bg-swan-blue/20'
  }
]
</script>

<template>
  <section class="py-32 relative overflow-hidden bg-white">
    <!-- Ambient background elements -->
    <div class="absolute top-0 left-1/4 w-96 h-96 bg-swan-blue/10 rounded-full blur-3xl pointer-events-none"></div>
    <div class="absolute bottom-0 right-1/4 w-96 h-96 bg-swan-silver/10 rounded-full blur-3xl pointer-events-none"></div>
    
    <!-- Background Swan Silhouette -->
    <div class="absolute top-1/2 left-0 w-64 h-64 opacity-[0.02] text-swan-deep pointer-events-none transform -translate-y-1/2 -rotate-12">
      <Swan />
    </div>

    <div class="max-w-6xl mx-auto px-6 relative z-10">
      <!-- Section Header -->
      <div class="mb-32 text-center reveal">
        <p class="text-[10px] tracking-[0.6em] uppercase text-swan-deep/30 mb-6 font-bold">The Chronicles</p>
        <h2 class="text-6xl md:text-8xl font-serif text-swan-deep leading-none relative inline-block">
          Kisah <span class="italic text-swan-silver">Cinta</span>
          <div class="absolute -bottom-4 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-swan-silver/40 to-transparent"></div>
        </h2>
      </div>

      <!-- Story Timeline -->
      <div class="space-y-40 md:space-y-64">
        <div v-for="(story, index) in stories" :key="index" 
             class="reveal relative flex flex-col md:flex-row items-center gap-12 md:gap-24"
             :class="index % 2 !== 0 ? 'md:flex-row-reverse' : ''">
          
          <!-- Large Decorative Number Background (Parallax) -->
          <div class="story-number absolute -top-20 md:-top-32 opacity-[0.03] select-none pointer-events-none font-serif text-[200px] md:text-[350px] leading-none"
               :class="index % 2 === 0 ? '-left-10 md:-left-20' : '-right-10 md:-right-20 text-right'">
            {{ story.number }}
          </div>

          <!-- Image/Visual Placeholder -->
          <div class="w-full md:w-1/2 relative group">
            <div class="aspect-[4/5] overflow-hidden rounded-[60px] md:rounded-[100px] relative z-10 shadow-2xl transition-transform duration-700 group-hover:scale-[1.02]">
              <div class="absolute inset-0 bg-gradient-to-b from-transparent to-swan-deep/20 z-10 pointer-events-none"></div>
              <img :src="story.img" :alt="'Chapter ' + story.number" class="w-full h-full object-cover parallax-img">
            </div>
            <!-- Decorative Offset Frame -->
            <div class="absolute -inset-4 border-2 border-swan-silver/20 rounded-[70px] md:rounded-[110px] -z-0 transform rotate-3 group-hover:rotate-0 transition-transform duration-700"></div>
          </div>

          <!-- Text Content -->
          <div class="w-full md:w-1/2 space-y-8 relative z-10" :class="index % 2 !== 0 ? 'md:text-right' : ''">
            <div class="flex flex-col" :class="index % 2 !== 0 ? 'md:items-end' : ''">
              <span class="text-swan-silver font-serif text-3xl italic mb-1">{{ story.year }}</span>
              <span class="text-swan-deep/20 font-bold tracking-[0.5em] uppercase text-xs">{{ story.date }}</span>
            </div>

            <h3 class="text-4xl md:text-5xl font-serif text-swan-deep leading-tight">
              {{ story.title }}
            </h3>

            <div class="space-y-6">
              <p class="text-lg text-swan-deep/60 leading-relaxed font-light">
                {{ story.desc }}
              </p>
              <div class="w-16 h-[1px] bg-swan-silver/40" :class="index % 2 !== 0 ? 'md:ml-auto' : ''"></div>
              <p class="text-sm text-swan-deep/40 italic">
                {{ story.extra }}
              </p>
            </div>
          </div>

        </div>
      </div>
    </div>

    <!-- Bottom Background Transition -->
    <div class="absolute bottom-0 left-0 w-full h-64 bg-gradient-to-t from-swan-gray to-transparent pointer-events-none"></div>
  </section>
</template>

// public/templates/Template 12/src/components/sections/LoveStory.tsx
"use client";

import React, { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Heart } from 'lucide-react';
import Image from 'next/image';
import VintageFrame from '../ui/VintageFrame';
import TornEdge from '../ui/TornEdge';
import VintageOrnament from '../ui/VintageOrnament';

const LoveStory = () => {
  const stories = [
    {
      date: "Januari 2024",
      title: "Awal Pertemuan",
      content: "Berawal dari pertemuan tak sengaja di sebuah perpustakaan kota, Anwar terkesima dengan ketenangan Cipung yang sedang asyik membaca buku. Sebuah teguran sederhana menjadi awal dari diskusi panjang tentang mimpi dan hobi yang ternyata saling bertautan.",
      image: "/assets/Image/galery3.webp"
    },
    {
      date: "Agustus 2025",
      title: "Menjalin Komitmen",
      content: "Setelah melewati berbagai suka dan duka bersama, Anwar dan Cipung memutuskan untuk melangkah ke jenjang yang lebih serius. Mereka menyadari bahwa perbedaan yang ada justru menjadi pelengkap sempurna dalam perjalanan hidup mereka menuju masa depan.",
      image: "/assets/Image/galery2.webp"
    },
    {
      date: "Maret 2027",
      title: "Menuju Ridha Allah",
      content: "Dengan restu dari kedua orang tua, kini Anwar dan Cipung siap mengikat janji suci di hadapan Allah SWT. Pernikahan ini bukanlah akhir, melainkan awal dari petualangan panjang yang akan mereka jalani bersama selamanya.",
      image: "/assets/Image/galery5.webp"
    }
  ];

  const containerRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start end", "end start"]
  });

  const ornamentY = useTransform(scrollYProgress, [0, 1], [-100, 100]);

  return (
    <section ref={containerRef} id="story" className="py-24 relative overflow-hidden bg-vintage-cream">
      <TornEdge position="top" />

      <div className="container mx-auto px-6 relative z-10 pt-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-20"
        >
          <p className="serif-text text-vintage-gold tracking-[0.6em] uppercase text-xs mb-4 weathered-text">Our Journey</p>
          <h2 className="script-text text-7xl text-vintage-brown gold-glow">Kisah Cinta</h2>
          <div className="w-24 h-[1px] bg-vintage-gold/40 mx-auto mt-8"></div>
        </motion.div>

        <div className="relative max-w-5xl mx-auto px-4">
          {stories.map((story, index) => (
            <div key={index} className={`relative flex flex-col ${index % 2 !== 0 ? 'md:flex-row-reverse' : 'md:flex-row'} items-center gap-10 md:gap-20 mb-32`}>
              {/* Image Side */}
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                className="w-full md:w-1/2"
              >
                <VintageFrame className="shadow-2xl">
                  <div className="relative aspect-[4/3] md:aspect-square">
                    <Image src={story.image} alt={story.title} fill className="object-cover" />
                  </div>
                </VintageFrame>
              </motion.div>

              {/* Content */}
              <motion.div
                initial={{ opacity: 0, x: index % 2 === 0 ? -50 : 50 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 1 }}
                className="w-full md:w-1/2 text-center md:text-left"
              >
                <div className={`bg-white/40 backdrop-blur-sm border border-vintage-gold/20 p-8 md:p-12 rounded-3xl shadow-xl hover:border-vintage-gold/50 transition-all group relative ${index % 2 === 0 ? 'md:border-l-4' : 'md:border-r-4'} border-vintage-gold`}>
                  {/* Decorative corner icon */}
                  <div className="absolute top-4 right-4 opacity-5 group-hover:opacity-10 transition-opacity">
                    <Heart size={40} />
                  </div>

                  <span className="serif-text text-vintage-gold font-bold text-sm tracking-[0.3em] uppercase">{story.date}</span>
                  <h3 className="serif-text text-2xl font-bold text-vintage-brown mt-3 mb-6 uppercase tracking-wider weathered-text">{story.title}</h3>
                  <p className="font-mono text-vintage-brown/90 leading-relaxed text-xs md:text-sm tracking-tighter border-l-2 border-vintage-gold/20 pl-4">
                    {story.content}
                  </p>
                </div>
              </motion.div>
            </div>
          ))}
        </div>
      </div>

      {/* Corner Ornaments */}
      <motion.div style={{ y: ornamentY }} className="absolute top-10 left-10 w-48 h-48 opacity-10 pointer-events-none rotate-180">
        <VintageOrnament />
      </motion.div>
      <motion.div style={{ y: ornamentY }} className="absolute bottom-10 right-10 w-48 h-48 opacity-10 pointer-events-none">
        <VintageOrnament />
      </motion.div>

      <TornEdge position="bottom" />
    </section>
  );
};

export default LoveStory;
