// public/templates/Template 7/src/components/OpeningScreen.vue
<script setup lang="ts">
import { MailOpen } from 'lucide-vue-next'
import { ref, onMounted } from 'vue'
import SakuraOrnament from './SakuraOrnament.vue'

defineEmits(['open'])

const guestName = ref('Tamu Undangan')

onMounted(() => {
  const urlParams = new URLSearchParams(window.location.search)
  const to = urlParams.get('to')
  if (to) {
    guestName.value = to.replace(/[-_]/g, ' ')
  }
})
</script>

<template>
  <div class="fixed inset-0 z-[100] overflow-y-auto bg-center bg-cover overflow-x-hidden" style="background-image: url('/assets/img/bg-new.webp');">
    <!-- Fixed background overlay (Optimized: no blur) -->
    <div class="fixed inset-0 bg-[#fff5f7]/85 pointer-events-none"></div>
    
    <!-- Decor Sakura Branch corner ornaments -->
    <SakuraOrnament position="top-right" class="w-64 h-64 md:w-96 md:h-96 opacity-60" />
    <SakuraOrnament position="bottom-left" class="w-64 h-64 md:w-96 md:h-96 opacity-40" />

    <!-- Content Container -->
    <div class="relative z-10 flex flex-col items-center justify-center min-h-[100vh] py-12 px-4 text-center w-full" data-aos="zoom-in">
      
      <!-- The Couple Photo -->
      <div class="relative mb-8 group shrink-0">
        <div class="absolute -inset-2 border-2 border-rose-gold/20 rounded-[100px] transform rotate-6 transition-transform group-hover:rotate-0 duration-1000"></div>
        <div class="w-40 h-40 md:w-48 md:h-48 rounded-[100px] border-[6px] border-white shadow-2xl overflow-hidden relative backdrop-blur-md">
           <img src="/assets/img/hero.webp" class="w-full h-full object-cover object-top transition-transform duration-700 group-hover:scale-110" />
        </div>
      </div>

      <div class="mb-6">
        <h1 class="text-4xl md:text-5xl lg:text-7xl font-serif text-rose-gold drop-shadow-xl text-shadow leading-tight">Razi & Seli</h1>
        <div class="section-divider mt-4 mb-2"></div>
        <h3 class="text-xs md:text-sm tracking-[0.4em] uppercase font-sans text-gray-500 font-bold">Undangan Pernikahan</h3>
      </div>
      
      <div class="mb-10 p-8 md:p-10 glass rounded-[40px] border border-white max-w-[90%] md:max-w-sm mx-auto shadow-2xl relative overflow-hidden shrink-0 group">
        <div class="absolute inset-0 bg-gradient-to-tr from-white/40 to-transparent pointer-events-none"></div>
        <div class="relative z-10">
          <p class="text-xs text-gray-400 mb-2 font-sans uppercase tracking-[0.2em] font-bold">Yth. Bapak / Ibu / Saudara/i</p>
          <p class="text-3xl md:text-4xl font-serif text-rose-gold mb-4 capitalize text-shadow">{{ guestName }}</p>
          <div class="section-divider w-12 mb-4"></div>
          <p class="text-xs md:text-sm font-sans font-light text-gray-600 leading-relaxed italic">Kami mengundang Anda untuk hadir di acara pernikahan kami.</p>
        </div>
      </div>
      
      <button @click="$emit('open')" class="flex items-center gap-3 px-10 py-4 text-white transition-all bg-rose-gold rounded-full shadow-2xl hover:bg-blush hover:shadow-rose-gold/40 hover:-translate-y-1 active:translate-y-0 group relative overflow-hidden shrink-0">
        <div class="absolute inset-0 bg-white/20 transform -translate-x-full group-hover:translate-x-full transition-transform duration-1000"></div>
        <MailOpen class="w-5 h-5 transition-transform group-hover:scale-110 relative z-10" />
        <span class="tracking-[0.2em] uppercase font-sans text-xs md:text-sm font-bold relative z-10">Buka Undangan</span>
      </button>
    </div>
  </div>
</template>

// public/templates/Template 12/src/components/sections/OpeningScreen.tsx
"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { MailOpen } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import Image from 'next/image';
import WaxSeal from '../ui/WaxSeal';
import VintageOrnament from '../ui/VintageOrnament';

interface OpeningScreenProps {
  onOpen: () => void;
}

const OpeningScreen: React.FC<OpeningScreenProps> = ({ onOpen }) => {
  const [isOpen, setIsOpen] = useState(false);
  const searchParams = useSearchParams();
  const guestName = searchParams.get('to') || 'Tamu Terhormat';

  const handleOpen = () => {
    setIsOpen(true);
    onOpen();
  };

  return (
    <AnimatePresence>
      {!isOpen && (
        <motion.div
          initial={{ opacity: 1 }}
          exit={{ opacity: 0, y: -100 }}
          transition={{ duration: 1.5, ease: "easeInOut" }}
          className="fixed inset-0 z-[10000] flex flex-col items-center justify-center bg-vintage-cream overflow-hidden"
        >
          {/* Background Texture & Grain */}
          <div className="paper-overlay"></div>
          <div className="grain-overlay grain-overlay-animated opacity-40"></div>
          <div className="vignette-overlay"></div>

          {/* Couple Photo Overlay */}
          <motion.div 
            initial={{ opacity: 0, scale: 1.1 }}
            animate={{ opacity: 0.12, scale: 1 }}
            transition={{ duration: 2, ease: "easeOut" }}
            className="absolute inset-0 z-0 pointer-events-none"
          >
            <Image 
              src="/assets/Image/overlay.webp" 
              alt="Couple" 
              fill 
              className="object-cover grayscale mix-blend-multiply"
            />
          </motion.div>

          {/* Decorative Ornaments */}
          <VintageOrnament className="absolute -top-10 -left-10 w-64 h-64 opacity-20 rotate-180 pointer-events-none grayscale sepia z-10" />
          <VintageOrnament className="absolute -bottom-10 -right-10 w-64 h-64 opacity-20 pointer-events-none grayscale sepia z-10" />

          <div className="relative z-20 flex flex-col items-center text-center px-6 max-w-2xl">
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 1 }}
              className="mb-8"
            >
              <WaxSeal text="A & C" />
            </motion.div>

            <motion.p
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5, duration: 0.8 }}
              className="serif-text text-vintage-brown/80 uppercase tracking-[0.5em] text-xs mb-4 weathered-text"
            >
              Wedding Invitation
            </motion.p>
            
            <motion.h1
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.8, duration: 1.2 }}
              className="script-text text-5xl sm:text-6xl md:text-8xl whitespace-nowrap text-vintage-brown mb-2 gold-glow"
            >
              Anwar & Cipung
            </motion.h1>

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1, duration: 0.8 }}
              className="serif-text text-vintage-gold font-bold tracking-[0.3em] mb-12 text-sm"
            >
              Rabu, 15 Maret 2027
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.2, duration: 0.8 }}
              className="mb-12"
            >
              <p className="serif-text text-vintage-brown/60 text-xs uppercase tracking-widest mb-4">Kepada Bapak/Ibu/Saudara/i</p>
              <div className="bg-white/30 backdrop-blur-sm border-y border-vintage-gold/20 py-6 px-10 rounded-3xl shadow-inner">
                <h2 className="serif-text text-2xl md:text-3xl text-vintage-brown font-bold tracking-wider">{guestName}</h2>
              </div>
              <p className="serif-text text-[10px] text-vintage-brown/40 mt-6 italic max-w-xs mx-auto leading-relaxed">
                Mohon maaf apabila ada kesalahan penulisan nama dan gelar.
              </p>
            </motion.div>

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleOpen}
              className="flex items-center gap-3 bg-vintage-brown text-vintage-cream px-10 py-4 rounded-xl shadow-2xl hover:bg-vintage-gold transition-all duration-300 group overflow-hidden relative"
            >
              <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/old-paper.png')] opacity-10"></div>
              <MailOpen size={18} className="group-hover:rotate-12 transition-transform" />
              <span className="serif-text font-bold tracking-[0.3em] uppercase text-xs">Open Invitation</span>
            </motion.button>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default OpeningScreen;
