// public/templates/Template 9/src/components/SaveTheDate.vue
<template>
  <section id="acara" class="py-20 px-6 bg-neo-white grid-bg border-b-8 border-neo-black relative overflow-hidden">
    <div class="absolute inset-0 bg-gradient-to-b from-transparent to-[var(--bg-main)] opacity-50 z-0"></div>
    
    <div class="max-w-5xl mx-auto flex flex-col md:flex-row items-center gap-12">
      <!-- Left: Big Text -->
      <div class="flex-1 text-center md:text-left relative z-10">
        <h2 class="text-neo-red text-xl font-black uppercase tracking-[0.2em] mb-4">Hitung Mundur</h2>
        <h3 class="text-[clamp(2.5rem,8vw,4.5rem)] font-black uppercase leading-[0.9] mb-8 tracking-tighter">
          NANTIKAN <br /> <span class="text-neo-red">MOMEN</span> <br /> KAMI
        </h3>
        <button 
          @click="saveToCalendar"
          class="neo-btn neo-btn-red text-neo-white inline-flex items-center gap-3"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
          SIMPAN DI KALENDER
        </button>
      </div>

      <!-- Right: Countdown Boxes -->
      <div class="flex-1 grid grid-cols-2 gap-4 w-full md:max-w-md relative">
        <!-- Floating shapes -->
        <div class="absolute -top-10 -right-10 w-24 h-24 bg-neo-blue border-4 border-neo-white rotate-12 -z-10"></div>
        <div class="absolute -bottom-10 -left-10 w-20 h-20 border-4 border-neo-red rotate-[-15deg] -z-10"></div>

        <div class="count-box">
          <span class="count-number">{{ timeLeft.days }}</span>
          <span class="count-label">Hari</span>
        </div>
        <div class="count-box bg-neo-red !text-white neo-shadow">
          <span class="count-number">{{ timeLeft.hours }}</span>
          <span class="count-label">Jam</span>
        </div>
        <div class="count-box bg-neo-blue !text-white neo-shadow">
          <span class="count-number">{{ timeLeft.minutes }}</span>
          <span class="count-label">Menit</span>
        </div>
        <div class="count-box">
          <span class="count-number">{{ timeLeft.seconds }}</span>
          <span class="count-label">Detik</span>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const targetDate = new Date('2027-03-15T10:00:00').getTime()
const timeLeft = ref({
  days: '00',
  hours: '00',
  minutes: '00',
  seconds: '00'
})

let timer = null

function updateCountdown() {
  const now = new Date().getTime()
  const distance = targetDate - now

  if (distance < 0) {
    clearInterval(timer)
    return
  }

  const d = Math.floor(distance / (1000 * 60 * 60 * 24))
  const h = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60))
  const m = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60))
  const s = Math.floor((distance % (1000 * 60)) / 1000)

  timeLeft.value = {
    days: d.toString().padStart(2, '0'),
    hours: h.toString().padStart(2, '0'),
    minutes: m.toString().padStart(2, '0'),
    seconds: s.toString().padStart(2, '0')
  }
}

function saveToCalendar() {
  const title = "Pernikahan Claude & Fanny"
  const details = "Acara Akad Nikah & Resepsi Claude & Fanny"
  const location = "RT 02, Desa Padang Jaya, Kec. Kuaro, Kab. Paser, Kalimantan Timur"
  const startDate = "20270315T100000"
  const endDate = "20270315T210000"
  const url = `https://www.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&dates=${startDate}/${endDate}&details=${encodeURIComponent(details)}&location=${encodeURIComponent(location)}`
  window.open(url, '_blank')
}

function handleVisibility() {
  if (document.hidden) {
    if (timer) clearInterval(timer)
  } else {
    updateCountdown()
    timer = setInterval(updateCountdown, 1000)
  }
}

onMounted(() => {
  updateCountdown()
  timer = setInterval(updateCountdown, 1000)
  document.addEventListener('visibilitychange', handleVisibility)
})

onUnmounted(() => {
  if (timer) clearInterval(timer)
  document.removeEventListener('visibilitychange', handleVisibility)
})
</script>

<style scoped>
</style>

// public/templates/Template 12/src/components/sections/SaveTheDate.tsx
"use client";

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Calendar } from 'lucide-react';
import FloralDivider from '../ui/FloralDivider';
import VintageOrnament from '../ui/VintageOrnament';

import { usePageVisibility } from '../../hooks/usePageVisibility';

const SaveTheDate = () => {
  const targetDate = new Date("2027-03-15T10:00:00").getTime();
  const isPageVisible = usePageVisibility();
  const [timeLeft, setTimeLeft] = useState({
    days: 0,
    hours: 0,
    minutes: 0,
    seconds: 0
  });

  useEffect(() => {
    if (!isPageVisible) return;

    const timer = setInterval(() => {
      const now = new Date().getTime();
      const distance = targetDate - now;

      if (distance < 0) {
        clearInterval(timer);
        return;
      }

      setTimeLeft({
        days: Math.floor(distance / (1000 * 60 * 60 * 24)),
        hours: Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)),
        minutes: Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60)),
        seconds: Math.floor((distance % (1000 * 60)) / 1000)
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [targetDate, isPageVisible]);

  const TimeUnit = ({ value, label }: { value: number, label: string }) => (
    <div className="flex flex-col items-center bg-vintage-ivory/50 border border-vintage-gold/20 p-2 md:p-4 rounded-xl min-w-[65px] md:min-w-[100px] shadow-sm backdrop-blur-sm">
      <span className="serif-text text-2xl md:text-4xl font-bold text-vintage-brown">{value}</span>
      <span className="serif-text text-[8px] md:text-xs uppercase tracking-widest text-vintage-gold mt-1">{label}</span>
    </div>
  );

  return (
    <section id="countdown" className="py-24 relative overflow-hidden bg-vintage-cream/50">
      <div className="container mx-auto px-6 relative z-10">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="text-center max-w-4xl mx-auto"
        >
          <h2 className="script-text text-6xl text-vintage-brown mb-4">Save The Date</h2>
          <p className="serif-text text-vintage-gold tracking-[0.3em] uppercase text-sm mb-12">Hitung Mundur</p>

          <div className="flex flex-wrap justify-center gap-2 md:gap-8 mb-16">
            <TimeUnit value={timeLeft.days} label="Hari" />
            <TimeUnit value={timeLeft.hours} label="Jam" />
            <TimeUnit value={timeLeft.minutes} label="Menit" />
            <TimeUnit value={timeLeft.seconds} label="Detik" />
          </div>

          <motion.div
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="inline-block"
          >
            <a
              href="https://calendar.google.com/calendar/render?action=TEMPLATE&text=The+Wedding+of+Anwar+%26+Cipung&dates=20270315T020000Z/20270315T080000Z&details=Pernikahan+Anwar+%26+Cipung&location=RT+02,+Desa+Padang+Jaya,+Kec.+Kuaro,+Kab.+Paser,+Kalimantan+Timur"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-3 bg-vintage-brown text-vintage-cream px-8 py-4 rounded-full shadow-xl hover:bg-vintage-gold transition-all duration-300 group"
            >
              <Calendar size={20} className="group-hover:rotate-12" />
              <span className="serif-text font-bold tracking-widest uppercase text-xs">Simpan di Kalender</span>
            </a>
          </motion.div>
        </motion.div>
      </div>

      {/* Decorative Ornaments */}
      <VintageOrnament className="absolute top-0 left-0 w-64 h-64 opacity-10 pointer-events-none" />
    </section>
  );
};

export default SaveTheDate;
